Repository k-krasilnikova/SUL, pull requests merged in 2021-12, with the labels that each got.

#9 [WIP] feat: add basic custom components (V1-003)
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Menu.tsx
  frontend/src/components/layout/styled.ts
  frontend/src/constants/routes.ts
  frontend/src/pages/Layout.tsx
Labels: feature

#13 fix: add correct components props(V1-003)
  frontend/package-lock.json
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/components/TextField/index.tsx
Labels: bug-fix

#15 Feature/v1-003: Configure theme for Client
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/components/TextField/index.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Menu.tsx
  frontend/src/components/layout/MyCoursesCounter.tsx
  frontend/src/components/layout/UserDropDown/UserDropDown.tsx
  frontend/src/components/layout/UserDropDown/UserDropDownContainer.tsx
  frontend/src/components/layout/UserDropDown/index.tsx
  frontend/src/components/layout/UserDropDown/styled.ts
  frontend/src/components/layout/styled.ts
  frontend/src/constants/routes.ts
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/themeSettings.ts
  frontend/src/types/user.ts
  frontend/tsconfig.json
Labels: feature

#16 Feature/v1-006: authentication of the clients using JWT
  backend/.env
  backend/.eslintignore
  backend/.eslintrc.json
  backend/babel.config.js
  backend/migrate-mongo-config.js
  backend/migrations/20211219190858-init_collections.js
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/constants.ts
  backend/src/db/connection/connectionMiddleware.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/.gitignore
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/auth/authInterfaces.ts
  backend/src/interfaces/db/entities.d.ts
  backend/src/interfaces/middleware/common.d.ts
  backend/src/modules/controllers/.gitignore
  backend/src/modules/controllers/authController.ts
  backend/src/modules/middlewares/authMiddleware.ts
  backend/src/modules/middlewares/loggerMiddleware.ts
  backend/src/modules/routes/.gitignore
  backend/src/modules/routes/accountRoutes.ts
  backend/src/modules/routes/routes.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/dto/dtoUtils.ts
  backend/src/utils/typeGuards/isError.ts
  backend/tsconfig.eslint.json
  backend/tsconfig.json
Labels: feature

#18 bug-fix: fix returned obj to plain js obj, refactor connection func
  backend/src/app.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/userProvider.ts
Labels: bug-fix

#20 Feature/v1-011: add husky pre-commit
  backend/.eslintrc.json
  backend/.husky/pre-commit
  backend/package-lock.json
  backend/package.json
Labels: feature

#19 feature v1-010 responsive profile page
  frontend/src/components/Avatar/Avatar.tsx
  frontend/src/components/Avatar/index.ts
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/layout/AuthorizedLayout.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/Header/MyCoursesCounter/MyCoursesCounter.tsx
  frontend/src/components/layout/UserDropDown/UserDropDown.tsx
  frontend/src/components/layout/UserDropDown/styled.ts
  frontend/src/components/layout/styled.ts
  frontend/src/icons/avatarDefault.svg
  frontend/src/icons/index.ts
  frontend/src/index.css
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/styled.ts
  frontend/src/themeSettings.ts
  frontend/src/types/user.ts
Labels: feature

#12 [v1-007 & v1-009] Added New SignIn page & Responsive Design
  .DS_Store
  backend/package-lock.json
  backend/package.json
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/SignIn/Definition/Definition.tsx
  frontend/src/pages/SignIn/Definition/index.ts
  frontend/src/pages/SignIn/Definition/styled.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/pages/SignIn/index.ts
  frontend/src/pages/SignIn/styled.tsx
  frontend/src/pages/index.ts
  frontend/src/store/.gitkeep
  frontend/src/themeSettings.ts
  frontend/src/types/signIn.ts
  frontend/src/utils/.gitkeep
  frontend/src/utils/Helpers/.gitkeep
  frontend/src/validations/signInValidationSchema.tsx
  frontend/tsconfig.json
Labels: required-changes

#22 feat: implement menu according to the role (V1-015)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button/index.ts
  frontend/src/components/Button/index.tsx
  frontend/src/components/TextField/index.ts
  frontend/src/components/TextField/index.tsx
  frontend/src/components/layout/Menu/Menu.tsx
  frontend/src/components/layout/Menu/MenuContainer.tsx
  frontend/src/components/layout/Menu/index.ts
  frontend/src/components/layout/Menu/styled.ts
  frontend/src/components/layout/styled.ts
  frontend/src/constants/menuRoles.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/Employees/Employees.tsx
  frontend/src/pages/Employees/index.ts
  frontend/src/pages/Requests/Requests.tsx
  frontend/src/pages/Requests/index.ts
  frontend/src/pages/Skills/Skills.tsx
  frontend/src/pages/Skills/index.ts
  frontend/src/pages/index.ts
  frontend/tsconfig.json
Labels: feature, required-changes

#21 feature/v1-008: getting user information
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/authProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/commonMiddleware.d.ts
  backend/src/interfaces/entities/user.d.ts
  backend/src/middlewares/authMiddleware.ts
  backend/src/middlewares/connectionMiddleware.ts
  backend/src/middlewares/loggerMiddleware.ts
  backend/src/modules/auth/authController.ts
  backend/src/modules/routes/accountRoutes.ts
  backend/src/modules/routes/routes.ts
  backend/src/modules/user/userController.ts
  backend/src/routing/accountRouter.ts
  backend/src/routing/routes.ts
  backend/src/routing/userRouter.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/dto/dtoUtils.ts
  backend/src/utils/validation/.gitignore
Labels: feature

#23 Feature/v1 021/connection to API for getting profile info
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/base.ts
  frontend/src/api/profile/getProfile.ts
  frontend/src/api/profile/index.ts
  frontend/src/constants/accessToken.ts
  frontend/src/constants/routes.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/ProfileContainer.tsx
  frontend/src/pages/Profile/index.ts
  frontend/src/types/user.ts
Labels: feature
