Repository k-krasilnikova/SUL, pull requests merged in 2022-04, with the labels that each got.

#309 fix/V1-130 - added new 10 courses
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220325075854-new_courses.js
  backend/src/interfaces/Ientities/IclientCourses.d.ts
Labels: bug-fix

#326 Feature/v1-074 Employees page
  frontend/src/api/manager/getEmployeesList.ts
  frontend/src/constants/employeeInfo.ts
  frontend/src/constants/messages.ts
  frontend/src/constants/routes.ts
  frontend/src/pages/Employees/Employees.tsx
  frontend/src/pages/Employees/EmployeesContainer.tsx
  frontend/src/pages/Employees/index.ts
  frontend/src/pages/Employees/styled.ts
  frontend/src/types/employee.ts
Labels: feature

#331 Bug/v1 100 | Fixed buttons styles for Learning Course
  frontend/src/components/Button/ButtonsEnums.ts
  frontend/src/components/Button/styled.ts
  frontend/src/pages/LearningCourse/styled.ts
Labels: bug

#335 Feature/v1-132 | Rank and stack implementations.
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220325075854-new_courses.js
  backend/src/interfaces/Ientities/IclientCourses.d.ts
Labels: feature

#339 Feature/v1-172 | Finish course sending fixed.
  frontend/src/api/test/sendTestResult.ts
Labels: bug

#340 bugfix/v1-132 | Synchronizing migrations
  backend/migrations/20220125143932-init_collections.js
Labels: bug-fix

#345 fix/V1-154 - fixed permission error for manager getting test
  backend/src/routing/clientCoursesRouter.ts
Labels: bug-fix

#342 Bug-fix/ 148 - myCourses pagination
  frontend/src/components/Course/Course.tsx
  frontend/src/constants/numbers.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/utils/helpers/arrays/isLastElem.ts
Labels: bug-fix

#344 Bugfix/v-168 fixed Completed button styles
  frontend/src/components/Button/styled.ts
Labels: bug-fix

#346 bug/v1-170 | Fixed redirect if test time is over
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
Labels: bug

#343 fix/V1-048 - added blacklist for tokens
  backend/src/controllers/auth/logout.ts
  backend/src/db/models/AccessTokens.ts
  backend/src/db/providers/authProvider.ts
  backend/src/middlewares/authMiddleware.ts
  backend/src/utils/auth/authUtils.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
Labels: bug-fix

#349 Feature/v1-180 | Error handling and logging updated.
  backend/package.json
  backend/src/middlewares/errorHandlingMiddleware.ts
  backend/src/middlewares/loggerMiddleware.ts
  backend/src/utils/log/logger.ts
  backend/src/utils/log/loggerHelper.ts
Labels: feature

#351 Bugfix/V1-074
  frontend/src/pages/Employees/styled.ts
Labels: bug-fix

#353 bug-fix/ delete button on details page
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
Labels: bug-fix

#350 Refactor/refactor LearningCourse container
  frontend/src/components/Button/HOC/withTimeLeft.tsx
  frontend/src/components/StartTestDialog/withStartTest.tsx
  frontend/src/hooks/useToggle.tsx
  frontend/src/pages/LearningCourse/ActionButton/ActionButton.tsx
  frontend/src/pages/LearningCourse/ActionButton/index.ts
  frontend/src/pages/LearningCourse/ActionButton/styled.ts
  frontend/src/pages/LearningCourse/CourseInfo/CourseInfo.tsx
  frontend/src/pages/LearningCourse/CourseInfo/index.ts
  frontend/src/pages/LearningCourse/CourseInfo/styled.ts
  frontend/src/pages/LearningCourse/CourseInfoToggle/CourseInfoToggle.tsx
  frontend/src/pages/LearningCourse/CourseInfoToggle/index.ts
  frontend/src/pages/LearningCourse/CourseInfoToggle/styled.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/Material/Material.tsx
  frontend/src/pages/LearningCourse/Material/MaterialContainer.tsx
  frontend/src/pages/LearningCourse/Material/index.ts
  frontend/src/pages/LearningCourse/Material/styled.ts
  frontend/src/pages/LearningCourse/StageController/StageController.tsx
  frontend/src/pages/LearningCourse/StageController/index.ts
  frontend/src/pages/LearningCourse/StageController/styled.ts
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/types/clientCourse.ts
Labels: required-changes

#359 bug/V1-182 | Changed the label btn to 'Continue' if user failed the test
  frontend/src/components/Button/HOC/withDisable.tsx
  frontend/src/constants/statuses.ts
Labels: bug

#362 fix/V1-130 - fixed mocked information about courses
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220325075854-new_courses.js
Labels: bug-fix

#348 Bug/v1 070 | Fixed bugs displayed for My course in mobile view
  frontend/src/components/Course/Course.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: required-changes

#361 V1-076 Bugfix: fixed EmployeeProfile page according to QA review
  frontend/src/api/employees/getEmployeeProfile.ts
  frontend/src/components/Button/ButtonsEnums.ts
  frontend/src/pages/EmployeeProfile/EmployeeCourses/EmployeeCourses.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfileContainer.tsx
  frontend/src/pages/EmployeeProfile/styled.ts
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/types/employee.ts
  frontend/src/utils/helpers/arrays/isLastElem.ts
Labels: bug-fix

#360 Feature/v1-176 | FE & BE paths refactored.
  backend/src/enums/routesEnum.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/routing/userRouter.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/components/Button/ActionButton.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResultItem.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResultItemContainer.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/Employees/EmployeesContainer.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/utils/helpers/paths/choosePath.ts
  frontend/src/utils/helpers/paths/transformRoute.ts
Labels: feature

#356 fix/V1-142 - Time for test and test results for client course
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220325075854-new_courses.js
  backend/src/controllers/tests/getTestResults.ts
  backend/src/db/models/ClientCourses.ts
Labels: bug-fix

#367 bug/v1 070 | Fixed path for mobile devices in My course page
  frontend/src/pages/CoursesList/CoursesList.tsx
Labels: bug

#366 improve/v1-181 | Changed queryKey strings to constants
  frontend/src/api/courses/getClientCourseAndMaterials.ts
  frontend/src/api/courses/getCourseInfo.ts
  frontend/src/api/courses/getCourseMaterials.ts
  frontend/src/api/courses/getPaginatedCourses.ts
  frontend/src/api/employees/getEmployeeCourses.ts
  frontend/src/api/employees/getEmployeeProfile.ts
  frontend/src/api/manager/approveRequest.ts
  frontend/src/api/manager/declineRequest.ts
  frontend/src/api/manager/getCoursesRequests.ts
  frontend/src/api/manager/getEmployeesList.ts
  frontend/src/api/myCourses/finishClientCourse.ts
  frontend/src/api/myCourses/getClientCourseInfo.ts
  frontend/src/api/myCourses/getClientCourses.ts
  frontend/src/api/myCourses/getClientPaginatedCourses.ts
  frontend/src/api/myCourses/passClientCourse.ts
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/api/profile/getProfile.ts
  frontend/src/api/test/getCourseTest.ts
  frontend/src/api/test/getTestTime.ts
  frontend/src/api/test/sendTestResult.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/api/userInfo/getUserInfo.ts
  frontend/src/constants/queryKeyConstants.ts
Labels: required-changes

#363 V1-177 - used debounce and fixed issue with many requests
  frontend/src/api/courses/searchAllCourses.ts
  frontend/src/api/myCourses/searchClientCourses.ts
  frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResultItemContainer.tsx
  frontend/src/constants/messages.ts
  frontend/src/constants/time.ts
Labels: feature, bug-fix

#369 V1-076/Bugfix: fixed Employee profile page according to new design
  frontend/src/components/Avatar/styled.ts
  frontend/src/pages/EmployeeProfile/AddCourseButton/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeCourses/EmployeeCourses.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
  frontend/src/pages/EmployeeProfile/styled.ts
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
Labels: feature, bug-fix

#370 fix/V1-130 - fixed some data issue
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220325075854-new_courses.js
Labels: bug-fix

#338 Feature/144 - skill calculation
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220325075854-new_courses.js
  backend/src/controllers/tests/getAchievments.ts
  backend/src/db/models/Course.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/utils/dto/skillsDto.ts
  backend/src/utils/skillsUtils.ts
Labels: feature

#377 V1-076 Bugfix: fixed Employee courses displaying
  frontend/src/api/employees/getEmployeeCourses.ts
  frontend/src/api/employees/index.ts
  frontend/src/api/manager/getEmployeeProfile.ts
  frontend/src/api/manager/index.ts
  frontend/src/pages/EmployeeProfile/EmployeeProfileContainer.tsx
  frontend/src/types/employee.ts
Labels: bug-fix

#368 Feature/v1-155 | Assign multiple courses endpoint and logics implemented.
  backend/src/controllers/manager/assignEmployeeCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/routing/employeesRouter.ts
  backend/src/utils/normaliser/queryCourses.ts
Labels: feature

#379 Bugfix/v1-127 | Invalid response bug fixed
  backend/src/controllers/clientCourses/finishCourse.ts
Labels: bug-fix

#371 fix/V1-048 - logout
  backend/src/app.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/auth/refresh.ts
  backend/src/db/providers/userProvider.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/base.ts
  frontend/src/constants/authConstants.tsx
  frontend/src/constants/routes.ts
  frontend/src/utils/helpers/deleteAllCookies.ts
Labels: bug-fix

#374 Improve/v1-187 | Fixed secure of pages depends on user roles
  frontend/src/App.tsx
  frontend/src/components/RoleRoute/RoleRoute.tsx
  frontend/src/constants/menuRoles.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
Labels: required-changes

#378 Feature/v1-161 | Implemented API endpoint for updating course info.
  backend/src/config/constants.ts
  backend/src/controllers/admin/editCourse.ts
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/controllers/clientCourses/manageAssessment.ts
  backend/src/controllers/clientCourses/startCourse.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/tests/getTestResults.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/routing/coursesRouter.ts
  backend/src/utils/normaliser/materials.ts
  backend/src/utils/normaliser/test.ts
  backend/src/utils/validation/isValidDescription.ts
  backend/src/utils/validation/isValidMaterials.ts
  backend/src/utils/validation/isValidQuestions.ts
  backend/src/utils/validation/isValidTechnologies.ts
Labels: feature

#382 refactor: change next button
  frontend/src/components/Button/ButtonsEnums.ts
  frontend/src/pages/LearningCourse/ActionButton/ActionButton.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: refactor

#384 fix/V1-177 - fix search issue
  frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
Labels: bug-fix

#383 Bug fix/V1-185 Redirect from Test Result
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/Profile/styled.ts
Labels: bug-fix

#387 fix/V1-177 - fix empty request
  frontend/src/api/courses/searchAllCourses.ts
Labels: bug-fix

#388 fix/V1-142
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220324225754-new_courses.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220325075854-new_courses.js
  frontend/src/components/CountDownTimer/CountDownTimer.tsx
  frontend/src/constants/time.ts
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/utils/helpers/convertTime.ts
Labels: bug-fix

#381 Feature/157 - skills and admin
  backend/src/controllers/skills/getAllSkills.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/Ientities/ISkillGroup.ts
  backend/src/routing/routes.ts
  backend/src/routing/skillsRouter.ts
Labels: feature

#392 Refactor | Refactored styles for body
  frontend/src/index.css
Labels: bug-fix, refactor

#365 feature/V1-159 - created functionality for deleting course by admin
  backend/src/controllers/admin/deleteCourse.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/routing/coursesRouter.ts
Labels: feature

#394 Bugfix/v1-155 | Fixed issue with not assigning courses after PRs merge
  backend/src/db/providers/clientCourseProvider.ts
Labels: bug-fix

#395 V1-076 Bugfix: fixed app routes for correct pages displaying
  frontend/src/App.tsx
Labels: bug-fix

#389 fix/V1-187 - fixed progress bar styles
  frontend/src/components/Course/Course.tsx
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/constants/progressBar.ts
  frontend/src/constants/test.ts
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/ResultProgressBar/ResultProgressBar.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/types/test.ts
  frontend/src/utils/helpers/convertCourseStatusToProgress.ts
Labels: bug-fix

#375 Feature/v1-169 Confirm Dialog on route switching
  frontend/src/hooks/index.ts
  frontend/src/hooks/useBlocker.tsx
  frontend/src/hooks/useCallbackPrompt.tsx
  frontend/src/pages/PassingTest/ConfirmLeavePage/ConfirmLeavePage.tsx
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/types/test.ts
Labels: feature

#399 fix/V1-177 - fix searching
  frontend/src/components/Layout/Header/SearchCourses/SearchCourses.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResult.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItem.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItemContainer.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/styled.ts
  frontend/src/components/Layout/Header/SearchCourses/types.ts
  frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
Labels: bug-fix

#397 Improve/v1-161 | Added ability to update course title and avatar.
  backend/src/controllers/admin/editCourse.ts
  backend/src/db/models/Course.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/utils/validation/isValidAvatar.ts
  backend/src/utils/validation/isValidTitle.ts
Labels: feature

#402 V1-076 ProgressBar styles on Employee profile courses
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/constants/progressBar.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/EmployeeCoursesList.tsx
  frontend/src/utils/helpers/convertCourseStatusToProgress.ts
Labels: feature, bug-fix

#401 fix/V1-159 - fix deleting course
  backend/src/controllers/admin/deleteCourse.ts
Labels: bug-fix

#404 Feature/v1-191 | Bug with nPerPage fixed.
  backend/src/db/providers/courseProvider.ts
Labels: bug

#405 Feature | v1-156 - Added functionality for adding multiple courses for employee
  frontend/src/api/manager/addCourseToEmployee.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/AddCourseDialogContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/CoursesList/styled.ts
Labels: feature

#412 Hot bug fix | V1-190 - fixed ui problems in dev. Changed deprecated value in eslint.
  backend/.prettierrc
  frontend/.prettierrc
  frontend/src/components/Button/ButtonVariants/styled.ts
  frontend/src/components/Image/styled.ts
  frontend/src/components/PDFViewer/PDFViewerButtons/styled.ts
  frontend/src/components/PDFViewer/PDFViewerDocument/styled.ts
  frontend/src/components/PDFViewer/styled.ts
  frontend/src/components/SnackbarProvider/styled.ts
  frontend/src/components/TextField/styled.ts
  frontend/src/pages/CoursesList/AddCourseButton/styled.ts
  frontend/src/pages/DetailedCourse/BackButton/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/SearchEmployeeCourse/styled.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/styled.ts
  frontend/src/pages/Employees/EmployeesList/styled.ts
  frontend/src/pages/PassingTest/TestResult/ResultDescription/styled.ts
  frontend/src/pages/PassingTest/TestResult/ResultProgressBar/styled.ts
  frontend/src/pages/PassingTest/TestTitleAndTimer/styled.ts
  frontend/src/pages/Profile/UserInfo/styled.ts
  frontend/src/pages/Requests/RequestItem/RequestButtons/styled.ts
  frontend/src/pages/SignIn/SignInForm/Definition/styled.tsx
  frontend/src/pages/SignIn/SignInForm/ErrorsMessenger/styled.ts
  frontend/src/pages/SignIn/SignInForm/styled.ts
  frontend/src/pages/SignIn/SignInImage/styled.ts
  frontend/src/pages/SignIn/styled.tsx
Labels: hot-fix

#408 Feature/v1-178 Change logic of drawing buttons
  frontend/src/components/Button/ButtonVariants/ActionButton.tsx
  frontend/src/components/ConfirmLogOut/ConfirmLogOut.tsx
  frontend/src/constants/ButtonLabels.ts
  frontend/src/constants/requests.tsx
  frontend/src/pages/CoursesList/AddCourseButton/AddCourseButton.tsx
  frontend/src/pages/CoursesList/CourseActions/CourseActions.tsx
  frontend/src/pages/DetailedCourse/BackButton/BackButton.tsx
  frontend/src/pages/DetailedCourse/BackButton/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourseActions/DetailedCourseActions.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButton/ActionButton.tsx
  frontend/src/pages/LearningCourse/CourseInfoToggle/CourseInfoToggle.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/PassingTest/ConfirmLeavePage/ConfirmLeavePage.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/styled.ts
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/SignIn/SignInForm/SignInForm.tsx
Labels: refactor, improvement

#419 V1-194 Bugfix: When a manager assigns courses to a user, these courses are displayed only after the page is refreshed
  frontend/src/api/manager/addCourseToEmployee.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/AddCourseDialogContainer.tsx
Labels: bug-fix

#420 Refactor | v1-160 - Changed text for DeleteCourseDialog
  frontend/src/constants/messages.ts
Labels: refactor

#421 V1-203 Bugfix: fixed SignIn form styles on responsive design
  frontend/src/pages/SignIn/SignInForm/styled.ts
Labels: bug-fix

#422 Bug fix | V1-196 - Added functionality for automatically passing first stage of course
  frontend/src/api/myCourses/passClientCourse.ts
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: bug, bug-fix

#406 Feature/v1 152 Added presentation type of the content
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations-backdev/20220411134739-add-notifications.js
  backend/migrations-backdev/20220411135726-added-types-for-materials.js
  backend/migrations/20220125143932-init_collections.js
  backend/migrations/20220411150120-added-types-for-materials.js
  backend/src/db/models/Course.ts
  backend/src/enums/materials.ts
  backend/src/interfaces/Ientities/Icourses.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PPViewer/PPViewer.tsx
  frontend/src/components/PPViewer/PPViewerContainer.tsx
  frontend/src/components/PPViewer/index.tsx
  frontend/src/components/PPViewer/types/index.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/Material/Material.tsx
  frontend/src/pages/LearningCourse/Material/MaterialContainer.tsx
  frontend/src/types/course.ts
  frontend/src/utils/helpers/materials/extractMaterial.ts
Labels: feature

#414 Feature/v1-189 | Passage time issue.
  backend/package-lock.json
  backend/package.json
  backend/src/config/constants.ts
  backend/src/controllers/tests/getTest.ts
  backend/src/controllers/tests/passTest.ts
  backend/src/controllers/tests/startTest.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/utils/date/testDate.ts
  backend/src/utils/validation/checkTestDate.ts
  backend/src/utils/validation/tests.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/test/sendTestResult.ts
  frontend/src/components/CountDownTimer/CountDownTimer.tsx
  frontend/src/constants/test.ts
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestTitleAndTimer/TestTitleAndTimer.tsx
  frontend/src/pages/PassingTest/types.ts
  frontend/src/pages/PassingTest/utils.ts
  frontend/src/types/clientCourse.ts
  frontend/src/types/test.ts
Labels: feature

#425 bug-fix/wrong left time calculation
  frontend/src/utils/helpers/convertTime.ts
Labels: bug-fix

#416 V1-163 Creating course endpoint
  backend/src/controllers/admin/addCourse.ts
  backend/src/controllers/admin/editCourse.ts
  backend/src/controllers/admin/preparingCourseData.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/routing/coursesRouter.ts
  backend/src/utils/validation/isValidComplexity.ts
  backend/src/utils/validation/isValidCourseData.ts
  backend/src/utils/validation/isValidDescription.ts
  backend/src/utils/validation/isValidText.ts
  backend/src/utils/validation/isValidTitle.ts
  frontend/src/api/myCourses/searchClientCourses.ts
Labels: feature

#429 Bugfix/v1-161 | Added timeout for editing test and updated materials validation.
  backend/src/controllers/admin/editCourse.ts
  backend/src/db/providers/testProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/utils/validation/isValidMaterials.ts
  backend/src/utils/validation/isValidTest.ts
  frontend/package-lock.json
Labels: bug-fix

#423 Feature/v1-201, v1-200 | Backend: Skills map API. Frontend: Added SkillsMap for Employee.
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
  backend/src/controllers/courses/getCoursesMap.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Ientities/IStackMember.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/routing/coursesRouter.ts
  backend/src/utils/comparator/ObjectId/compareObjectIds.ts
  backend/src/utils/normaliser/courses.ts
  backend/src/utils/normaliser/employees.ts
  backend/src/utils/typeConversion/common.ts
  backend/src/utils/typeConversion/courses/coursesTypeConversions.ts
  frontend/src/api/courses/getCoursesMap.ts
  frontend/src/api/courses/index.ts
  frontend/src/components/CoursePlate/CoursePlate.tsx
  frontend/src/components/CoursePlate/index.ts
  frontend/src/components/CoursePlate/styled.ts
  frontend/src/constants/queryKeyConstants.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/skillsMap.tsx
  frontend/src/pages/PassingTest/types.ts
  frontend/src/pages/SkillsMap/SkillsMap.tsx
  frontend/src/pages/SkillsMap/SkillsMapContainer.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CourseMapForCurrentStack.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/Course/Course.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/Course/CourseContainer.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/Course/index.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/Course/styled.ts
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/CoursesList.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/index.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/styled.ts
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/index.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/styled.ts
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/utils.ts
  frontend/src/pages/SkillsMap/StackMap/StackMap.tsx
  frontend/src/pages/SkillsMap/StackMap/index.ts
  frontend/src/pages/SkillsMap/StackMap/styled.ts
  frontend/src/pages/SkillsMap/index.ts
  frontend/src/pages/SkillsMap/styled.ts
  frontend/src/pages/SkillsMap/types/index.ts
  frontend/src/types/course.ts
Labels: feature

#409 Feature/v1-158 | Implemented UI of the Skill page for Admin
  frontend/src/api/skills/getAllSkills.ts
  frontend/src/api/skills/index.ts
  frontend/src/api/skills/searchSkills.ts
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/SkillGroup/SkillGroup.tsx
  frontend/src/components/SkillGroup/SkillItem/SkillItem.tsx
  frontend/src/components/SkillGroup/SkillItem/index.ts
  frontend/src/components/SkillGroup/SkillItem/styled.ts
  frontend/src/components/SkillGroup/index.ts
  frontend/src/components/SkillGroup/styled.ts
  frontend/src/components/SkillGroup/types/index.ts
  frontend/src/constants/queryKeyConstants.ts
  frontend/src/constants/routes.ts
  frontend/src/enums/sizes.ts
  frontend/src/pages/Skills/Skills.tsx
  frontend/src/pages/Skills/SkillsContainer.tsx
  frontend/src/pages/Skills/index.ts
  frontend/src/pages/Skills/styled.ts
  frontend/src/pages/Skills/types/index.ts
  frontend/src/types/skill.ts
  frontend/src/types/user.ts
Labels: feature

#430 Bug/v1-187 | Fixed RoleRoute after reloading the page
  frontend/src/components/Routes/RoleRoute.tsx
  frontend/src/components/Routes/types/index.ts
Labels: bug

#437 Bugfix/v1-201 | Skills map correct redirect
  backend/src/controllers/courses/getCoursesMap.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/utils/normaliser/courses.ts
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/Course/Course.tsx
  frontend/src/pages/SkillsMap/StackMap/CourseMapForCurrentStack/CoursesList/CoursesList.tsx
  frontend/src/pages/SkillsMap/StackMap/StackMap.tsx
  frontend/src/pages/SkillsMap/types/index.ts
  frontend/src/types/course.ts
Labels: bug-fix

#438 Bug/v1-195 | Long name of course title on Employee Profile page for Manager
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/CourseItem.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/CourseItemContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/index.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/types/index.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/EmployeeCoursesList.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/styled.ts
  frontend/src/types/employee.ts
Labels: bug, refactor

#439 bug/v1-211 | Fixed displaying stack on Employee for Manager
  frontend/src/pages/EmployeeProfile/EmployeeInfo/EmployeeInfo.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/EmployeeItem.tsx
  frontend/src/types/employee.ts
Labels: bug

#436 Bugfix: fix points for new skills
  backend/src/controllers/tests/getAchievments.ts
  backend/src/db/providers/skillProvider.ts
Labels: bug-fix

#443 bug/v1-195 | Fixed width for course title in Employee profile page
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/styled.ts
Labels: bug

#434 V1-197 Similar courses functionality
  backend/migrations-backdev/20220421091129-added-similar-courses.js
  backend/migrations/20220425153600-added-similar-courses.js
  backend/src/controllers/admin/addCourse.ts
  backend/src/controllers/admin/preparingCourseData.ts
  backend/src/controllers/clientCourses/getClientCourse.ts
  backend/src/controllers/courses/getAllCourses.ts
  backend/src/controllers/courses/getCourse.ts
  backend/src/db/models/Course.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/utils/normaliser/prepareSimilarCourses.ts
  backend/src/utils/typeConversion/courses/coursesTypeConversions.ts
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/base.ts
  frontend/src/components/Course/CourseInfo/CourseInfo.tsx
  frontend/src/constants/detailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/SimilarCourses/SimilarCourses.tsx
  frontend/src/types/course.ts
  frontend/src/types/detailedCourse.ts
Labels: feature, bug-fix

#444 Bug/v1-210 | Fixed migrations issues.
  backend/migrations-backdev/20220411135726-added-types-for-materials.js
  backend/migrations/20220411150120-added-types-for-materials.js
Labels: bug

#447 V1-197 - fixed error 500 for courses without similar courses
  backend/migrations-backdev/20220421091129-added-similar-courses.js
  backend/migrations/20220425153600-added-similar-courses.js
Labels: hot-fix

#442 bug/v1-213 | Fixed search for mobile
  frontend/src/api/courses/searchAllCourses.ts
  frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
Labels: bug

#453 V1-163 - fixed exercise for creating course
  backend/src/db/models/Course.ts
Labels: bug-fix

#440 Feature/v1-208 | New course validation rules.
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/admin/editCourse.ts
  backend/src/controllers/admin/preparingCourseData.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/interfaces/dto/courses.ts
  backend/src/utils/string/capitalizeFirstLetter.ts
  backend/src/utils/string/fullTrim.ts
  backend/src/utils/validation/courses/constants.ts
  backend/src/utils/validation/courses/index.ts
  backend/src/utils/validation/courses/isValidAvatar.ts
  backend/src/utils/validation/courses/isValidComplexity.ts
  backend/src/utils/validation/courses/isValidCourseData.ts
  backend/src/utils/validation/courses/validateDescription.ts
  backend/src/utils/validation/courses/validateMaterials.ts
  backend/src/utils/validation/courses/validateTechnologies.ts
  backend/src/utils/validation/courses/validateTest.ts
  backend/src/utils/validation/courses/validateTitle.ts
  backend/src/utils/validation/isValidComplexity.ts
  backend/src/utils/validation/isValidMaterials.ts
  backend/src/utils/validation/isValidTechnologies.ts
  backend/src/utils/validation/isValidTest.ts
  backend/src/utils/validation/isValidText.ts
  backend/src/utils/validation/schemas/courses.ts
  backend/src/utils/validation/strings/index.ts
  backend/src/utils/validation/strings/isNotNumberOnly.ts
  backend/src/utils/validation/strings/isNotSpecialsOnly.ts
Labels: feature, wip

#446 Feature/v1-158 | Fixed issues that founded while testing
  frontend/src/components/SkillGroup/SkillItem/SkillItem.tsx
  frontend/src/components/SkillGroup/SkillItem/SkillItemContainer.tsx
  frontend/src/components/SkillGroup/SkillItem/index.ts
  frontend/src/components/SkillGroup/SkillItem/styled.ts
  frontend/src/components/SkillGroup/styled.ts
  frontend/src/components/SkillGroup/types/index.ts
  frontend/src/pages/Skills/SkillsContainer.tsx
  frontend/src/pages/Skills/styled.ts
Labels: bug

#451 Refactor | V1-205,206,207 - Refactor UI on Emploees, Employee Profile, Pending Requests pages
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/UserProfile/UserAvatar/UserAvatar.tsx
  frontend/src/components/UserProfile/UserAvatar/index.ts
  frontend/src/components/UserProfile/UserAvatar/styled.ts
  frontend/src/components/UserProfile/UserInfo/CopyName/CopyName.tsx
  frontend/src/components/UserProfile/UserInfo/CopyName/CopyNameContainer.tsx
  frontend/src/components/UserProfile/UserInfo/CopyName/index.ts
  frontend/src/components/UserProfile/UserInfo/CopyName/styled.ts
  frontend/src/components/UserProfile/UserInfo/UserInfo.tsx
  frontend/src/components/UserProfile/UserInfo/UserInfoItem/UserInfoItem.tsx
  frontend/src/components/UserProfile/UserInfo/UserInfoItem/index.ts
  frontend/src/components/UserProfile/UserInfo/UserInfoItem/styled.ts
  frontend/src/components/UserProfile/UserInfo/index.ts
  frontend/src/components/UserProfile/UserInfo/styled.ts
  frontend/src/components/UserProfile/UserProfile.tsx
  frontend/src/components/UserProfile/index.ts
  frontend/src/components/UserProfile/styled.ts
  frontend/src/components/UserProfile/types.ts
  frontend/src/constants/employeeInfo.ts
  frontend/src/constants/messages.ts
  frontend/src/constants/profile.ts
  frontend/src/constants/userInfo.ts
  frontend/src/enums/sizes.ts
  frontend/src/index.css
  frontend/src/pages/EmployeeProfile/EmployeeInfo/EmployeeInfo.tsx
  frontend/src/pages/EmployeeProfile/EmployeeInfo/index.ts
  frontend/src/pages/EmployeeProfile/EmployeeInfo/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfileContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/styled.ts
  frontend/src/pages/EmployeeProfile/styled.ts
  frontend/src/pages/EmployeeProfile/types.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/EmployeeItem.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/styled.ts
  frontend/src/pages/Employees/EmployeesList/styled.ts
  frontend/src/pages/Employees/styled.ts
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/PassingTest/styled.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/UserInfo/UserInfo.tsx
  frontend/src/pages/Profile/UserInfo/styled.ts
  frontend/src/pages/Profile/styled.ts
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/Requests/RequestItem/RequestButtons/styled.ts
  frontend/src/pages/Requests/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/RequestItem/styled.ts
  frontend/src/themeSettings.ts
  frontend/src/types/employee.ts
  frontend/src/types/profile.ts
  package-lock.json
Labels: refactor
