Repository k-krasilnikova/SUL, pull requests merged in 2022-03, with the labels that each got.

#208 bugfix/v1-070/responsive my courses fixed
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/CourseInfo.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
  frontend/src/components/Layout/MobileSearch/index.ts
  frontend/src/components/Layout/MobileSearch/styled.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/constants/pages.ts
  frontend/src/index.css
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/utils/helpers/getWindowWidth.ts
  frontend/src/utils/helpers/shortifyCourseDescription.ts
Labels: bug-fix

#209 [Bugfix]:env-fix - Ignoring .env rule.
  backend/.env
  backend/.gitignore
Labels: bug-fix

#213 V1-106 - fix refetching profile data on all pages
  frontend/src/api/profile/getProfile.ts
  frontend/src/api/userInfo/getUserInfo.ts
Labels: bug-fix

#212 hotfix/v1-070
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
Labels: hot-fix

#218 [bugfix/signinput-color] bugfix according review
  frontend/src/components/TextField/TextField.tsx
  frontend/src/constants/signStyle.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/pages/SignIn/styled.tsx
  frontend/src/types/signIn.ts
Labels: hot-fix, bug-fix

#220 bugfix V1-092 The updated design for the Details page
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
Labels: bug-fix

#227 V1-105 - deleted mock data for Details page, used data from database
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/types/clientCourse.ts
  frontend/src/types/course.ts
Labels: bug-fix

#230 Bugfix/v1-092 Disabled button on Detailed course page
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/styled.ts
Labels: bug-fix

#229 Bugfix V1-096 "Completed" button on the course card
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
Labels: feature, bug-fix

#225 V1-101 Responsive design for Test & Result pages
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/icons/checkbox.svg
  frontend/src/icons/checkboxChecked.svg
  frontend/src/pages/PassingTest/QuestionItem/styled.ts
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/styled.ts
  frontend/src/pages/PassingTest/styled.ts
Labels: feature

#234 V1-111 Updated arrow style on the Learning materials page
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/styled.ts
Labels: feature

#231 [WIP] Feature/v1-097 | Implement proper skills data and relations structure.
  .DS_Store
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/controllers/courses/getAllCourses.ts
  backend/src/controllers/courses/getCourse.ts
  backend/src/controllers/tests/getAchievments.ts
  backend/src/controllers/user/getProfileInfo.ts
  backend/src/db/models/Course.ts
  backend/src/db/models/Skill.ts
  backend/src/db/models/SkillGroup.ts
  backend/src/db/models/User.ts
  backend/src/db/models/UserSkill.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Ientities/ISkill.ts
  backend/src/interfaces/Ientities/ISkillGroup.ts
  backend/src/interfaces/Ientities/IUserSkill.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/utils/dto/skillsDto.ts
  backend/src/utils/validation/checkDuplicates.ts
Labels: feature

#237 [bugfix/v1-097] - Fixed issues with technologies in models and migrations
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
  backend/src/db/models/Course.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/interfaces/Ientities/Imaterials.ts
Labels: bug-fix

#232 Feature/mail-notifications
  backend/package-lock.json
  backend/package.json
  backend/src/classes/Mail/Mail.ts
  backend/src/config/constants.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/middlewares/mailSender.ts
  backend/src/routing/pendingCourses.ts
Labels: feature, required-changes

#235 V1-098 Implement snackbars all over the app
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/courses/applyCourse.ts
  frontend/src/api/courses/getCourseInfo.ts
  frontend/src/api/courses/getCourses.ts
  frontend/src/api/logOut/logOut.tsx
  frontend/src/api/myCourses/finishClientCourse.ts
  frontend/src/api/myCourses/getMyCourseInfo.ts
  frontend/src/api/myCourses/getMyCourses.ts
  frontend/src/api/myCourses/passClientCourse.ts
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/api/profile/getProfile.ts
  frontend/src/api/test/getCourseTest.ts
  frontend/src/api/test/sendTestResult.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/api/userInfo/getUserInfo.ts
  frontend/src/components/SnackbarProvider/SnackbarProvider.tsx
  frontend/src/components/SnackbarProvider/index.ts
  frontend/src/components/SnackbarProvider/styled.ts
  frontend/src/constants/authConstants.tsx
  frontend/src/constants/snackbarVariant.tsx
  frontend/src/index.tsx
  frontend/src/types/course.ts
Labels: feature

#238 Feature/v1-095 - implement displaying primary/not tech group
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Ientities/Iusers.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/ProfileContainer.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/UserSkillsContainer.tsx
  frontend/src/types/skill.ts
  frontend/src/types/user.ts
  frontend/src/utils/helpers/isSkillCompleted.ts
Labels: feature

#239 V1-096 Bugfix/Completed button
  frontend/src/pages/CoursesList/styled.ts
Labels: bug-fix

#241 feature/auto-delete rejected courses
  backend/src/config/constants.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/middlewares/mailSender.ts
  backend/src/utils/validation/checkDuplicates.ts
Labels: feature

#245 bugfix/v1-099
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/Header/SearchCourses/SearchCourses.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
  frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
  frontend/src/constants/snackbarVariant.tsx
  frontend/src/utils/helpers/searchHelpers/checkSpace.ts
  frontend/src/utils/helpers/searchHelpers/formatInputValue.ts
  frontend/src/utils/helpers/searchHelpers/index.ts
Labels: bug-fix

#244 V1-115 Bugfix Passing test and course
  frontend/src/api/courses/index.ts
  frontend/src/api/myCourses/getClientCourseInfo.ts
  frontend/src/api/myCourses/getClientCourses.ts
  frontend/src/api/myCourses/index.ts
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
Labels: bug-fix

#254 fix/V1-112 - fix error when auth is failed
  frontend/src/pages/SignIn/ErrorsMessager/ErrorsContainer.tsx
  frontend/src/pages/SignIn/ErrorsMessager/ErrorsMessenger.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/types/signIn.ts
Labels: bug-fix

#249 Bugfix V1-120 & V1-114
  frontend/src/components/Course/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/types/detailedCourse.ts
Labels: bug-fix

#253 Bug/v1-117
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/styled.ts
Labels: bug

#223 bugfix/v1-070/my courses responsive fixed
  frontend/src/components/Course/CourseInfo.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/constants/windowWidth.ts
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/utils/helpers/getWindowWidth.ts
  frontend/src/utils/helpers/shortifyCourseDescription.ts
Labels: bug-fix, required-changes

#256 V1-120 fixed button displaying on the Details page
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
Labels: hot-fix

#257 bug/v1-117
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
Labels: bug

#258 Bug-fix/109
  backend/src/config/constants.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/routing/pendingCourses.ts
  frontend/package-lock.json
  frontend/src/components/Button/DeclinedButton.tsx
  frontend/src/constants/time.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/types/clientCourse.ts
  frontend/src/types/detailedCourse.ts
  frontend/src/utils/helpers/convertTestTimeout.ts
  frontend/src/utils/helpers/convertTime.ts
Labels: feature, bug-fix

#252 Bugfix/v1-119 | Blank test result page
  backend/src/controllers/tests/getAchievments.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/utils/comparator/ObjectId/compareObjectIds.ts
  backend/src/utils/comparator/ObjectId/containsObjectId.ts
  backend/src/utils/dto/skillsDto.ts
  backend/src/utils/normaliser/skills.ts
  backend/src/utils/technologies/userTechnologies.ts
Labels: bug-fix

#267 Fix of bugfix/v1-124 | clientCourse detailed issue with status fixed [URGENT]
  backend/src/controllers/clientCourses/getClientCourse.ts
Labels: bug-fix

#268 bugfix/v1-099/search functioning
  frontend/src/components/Layout/Header/SearchCourses/SearchCourses.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/utils/helpers/searchHelpers/checkSpace.ts
  frontend/src/utils/helpers/searchHelpers/formatInputValue.ts
Labels: bug-fix

#263 feature/v1-100 - responsive design for Learning Course
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/styled.ts
Labels: feature

#269 Bugfix/v1-113 | Redirect to detailed course page after clicking on submit
  frontend/src/api/test/sendTestResult.ts
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/types/test.ts
Labels: bug-fix

#265 bug/v1-117/fixed starting test & continue learning
  frontend/src/api/myCourses/startClientCourse.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: bug

#273 Hotfix FE: removed extra course status
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: hot-fix

#276 V1-131 Bugfix blank Learning page
  backend/src/db/providers/courseProvider.ts
  frontend/src/api/courses/getCourseMaterials.ts
  frontend/src/api/courses/index.ts
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/types/course.ts
Labels: feature, bug-fix

#278 fix/V1-130 - Added more mocked courses and skills for manager
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
Labels: feature

#280 bug/v1-133 | Fixed issue with the blank screen after reloading page for logged user
  frontend/src/App.tsx
  frontend/src/components/PrivateRoute/PrivateRoute.tsx
Labels: bug

#281 V1-135 Course labels of search result item
  frontend/src/components/Label/Label.tsx
  frontend/src/components/Label/index.ts
  frontend/src/components/Label/styled.ts
  frontend/src/components/Layout/Header/SearchCourses/SearchResultItem.tsx
  frontend/src/components/Layout/Header/SearchCourses/SearchResultItemContainer.tsx
Labels: feature

#283 feature/v1-135 | On the Learning page, some videos are broken
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
Labels: bug

#285 fix/V1-102 - Course images centered in the image area
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/migrations/20220125143932-init_collections.js
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/styled.ts
Labels: bug-fix

#286 V1-101 Bugfix: fixed Test&Result styles
  frontend/src/pages/PassingTest/QuestionItem/styled.ts
  frontend/src/pages/PassingTest/TestResult/styled.ts
  frontend/src/pages/PassingTest/styled.ts
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: bug-fix

#284 Bugfix/v1-131 | Fixed unnecessary (500) materials request.
  frontend/src/api/courses/getClientCourseAndMaterials.ts
  frontend/src/api/courses/index.ts
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: bug-fix

#290 bug/v1-133 | Fixed issue with the blank screen for authorized user
  frontend/src/App.tsx
  frontend/src/components/PrivateRoute/PrivateRoute.tsx
Labels: bug

#291 Feature V1-077 | Implement getting of employee courses for manager
  backend/src/controllers/manager/getEmployeeInfo.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/routing/employeesRouter.ts
  backend/src/utils/normaliser/employees.ts
Labels: feature

#266 Feature/v1-122 Infinite scroll
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/courses/getCourses.ts
  frontend/src/api/courses/getPaginatedCourses.ts
  frontend/src/api/courses/index.ts
  frontend/src/api/myCourses/getClientCourses.ts
  frontend/src/api/myCourses/getClientPaginatedCourses.ts
  frontend/src/api/myCourses/index.ts
  frontend/src/components/Course/Course.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/types/responseDataMyCourses.ts
Labels: feature

#288 bugfix/v1-070/fixed courses ui bugs
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/CourseContainer.tsx
  frontend/src/components/Course/index.ts
  frontend/src/components/Course/styled.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/constants/progressBar.ts
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/utils/helpers/shortifyCourseDescription.ts
Labels: bug-fix

#299 bug/v1-134 | Fixed issue when passed test displayed only after reloading profile page
  frontend/src/api/test/sendTestResult.ts
Labels: bug

#302 bug/v1-137/displaying search result
  frontend/src/components/Course/styled.ts
Labels: bug

#304 V1-101 Bugfix: fixed responsive test answer length
  frontend/src/pages/PassingTest/QuestionItem/styled.ts
Labels: bug-fix

#305 Bugfix/v1-131 | Fixed lost changes after unsuccessful conflict solving.
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: bug

#306 Bug/v1 140 | Fixed long skill names going out of the border & added hover to showing full skill name
  frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: bug

#313 bug/v1-136/search courses
  backend/src/db/providers/courseProvider.ts
  backend/src/utils/decode/decodeSearchParams.ts
  frontend/src/api/courses/searchAllCourses.ts
Labels: bug

#292 fix/V1-143 - Progress bar on details page
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/enums/coursesEnums.ts
  frontend/package-lock.json
  frontend/src/constants/detailedCourse.tsx
  frontend/src/constants/statuses.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/types/detailedCourse.ts
  frontend/src/utils/helpers/convertStatusToProgress.ts
  frontend/src/utils/helpers/convertTime.ts
Labels: bug-fix

#312 bugfix/v1-100/fixed learning page styles
  frontend/src/index.css
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/styled.ts
Labels: bug-fix

#317 bug-fix/added loader if testData is fetching
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/types/test.ts
Labels: bug-fix

#318 bug-fix/added redirect
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
Labels: bug-fix

#322 bug-fix/v1-138 | refactor after QA testing
  frontend/src/constants/statuses.ts
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
Labels: bug-fix

#324 Feature/v1-149 | Shortened info being sent about employees.
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/src/controllers/manager/getEmployeeInfo.ts
  backend/src/controllers/manager/getEmployees.ts
  backend/src/db/models/Course.ts
  backend/src/db/models/StackMember.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/enums/users.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Ientities/IStackMember.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/interfaces/common/users.ts
  backend/src/utils/normaliser/employees.ts
Labels: feature

#325 fix: timeout fails test
  frontend/src/api/myCourses/finishClientCourse.ts
  frontend/src/api/test/sendTestResult.ts
  frontend/src/components/Button/ActionButton.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
Labels: bug-fix

#319 Feature/v1-127 | Assessments feature.
  backend/src/config/constants.ts
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/controllers/clientCourses/manageAssessment.ts
  backend/src/controllers/manager/adapterManager.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/tests/getAchievments.ts
  backend/src/controllers/tests/getTestResults.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/enums/common.ts
  backend/src/enums/coursesEnums.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/routing/clientCoursesRouter.ts
  frontend/src/components/Button/HOC/withDisable.tsx
  frontend/src/components/StartTestDialog/withStartTest.tsx
  frontend/src/constants/snackbarVariant.tsx
  frontend/src/constants/statuses.ts
  frontend/src/constants/test.ts
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/types/detailedCourse.ts
  frontend/src/types/test.ts
Labels: feature

#323 fix/V1-143 - fixed some styles
  frontend/src/api/logOut/logOut.tsx
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
Labels: bug-fix

#327 Feature/v1-145 | Fixed bug with videos not played.
  frontend/src/utils/helpers/videoPlayer/videoLink.ts
Labels: bug-fix

#329 Bugfix/v1-129 Requests page styles
  frontend/src/components/Avatar/styled.ts
  frontend/src/pages/Requests/RequestItem/styled.ts
  frontend/src/pages/Requests/Requests.tsx
  frontend/src/pages/Requests/styled.ts
Labels: bug-fix
