Repository k-krasilnikova/SUL, pull requests merged in 2022-05, with the labels that each got.

#458 Refactor | V1-206 - Refactor Employee page UI
  frontend/src/constants/employeeInfo.ts
  frontend/src/constants/employeesPage.ts
  frontend/src/constants/windowWidth.ts
  frontend/src/enums/employee.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetWindowSizeLabel.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/Employees/Employees.tsx
  frontend/src/pages/Employees/EmployeesContainer.tsx
  frontend/src/pages/Employees/EmployeesList/ContentColumn/ContentColumn.tsx
  frontend/src/pages/Employees/EmployeesList/ContentColumn/index.ts
  frontend/src/pages/Employees/EmployeesList/ContentColumn/styled.ts
  frontend/src/pages/Employees/EmployeesList/ContentGrid/ContentGrid.tsx
  frontend/src/pages/Employees/EmployeesList/ContentGrid/ContentGridContainer.tsx
  frontend/src/pages/Employees/EmployeesList/ContentGrid/index.ts
  frontend/src/pages/Employees/EmployeesList/ContentGrid/styled.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/EmployeeContent.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/EmployeeContentContainer.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/index.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/styled.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/EmployeeItem.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/EmployeeItemContainer.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/index.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeItem/styled.ts
  frontend/src/pages/Employees/EmployeesList/EmployeesList.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeesListContainer.tsx
  frontend/src/pages/Employees/EmployeesList/index.ts
  frontend/src/pages/Employees/EmployeesList/styled.ts
  frontend/src/pages/Employees/styled.ts
  frontend/src/pages/Employees/types.ts
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/themeSettings.ts
  frontend/src/types/employee.ts
  frontend/src/utils/helpers/getWindowLabelByWidth.ts
  frontend/src/utils/helpers/getWindowWidth.ts
Labels: refactor

#461 Hot-fix | V1-206 - Fixed types warning
  frontend/src/hooks/useGetWindowSizeLabel.tsx
  frontend/src/pages/Employees/EmployeesList/ContentGrid/ContentGrid.tsx
Labels: hot-fix

#454 V1-163 - unique titles have been fixed
  backend/src/db/models/Course.ts
  backend/src/db/models/Tests.ts
Labels: bug, bug-fix

#455 V1-197 - added similar courses for editing
  backend/src/controllers/admin/editCourse.ts
  backend/src/db/providers/courseProvider.ts
Labels: bug, bug-fix

#456 Feature/v1-199 | Implemented pending assessments page.
  backend/src/controllers/manager/getPendingAssessments.ts
  backend/src/controllers/tests/getAchievments.ts
  backend/src/controllers/tests/sendTestResults.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/utils/normaliser/skills.ts
  backend/src/utils/typeConversion/clientCourses/clientCoursesTypeConversions.ts
  backend/src/utils/typeConversion/datetime/datetimeTypeConversions.ts
  backend/src/utils/typeConversion/skills/skillsAndTechs.ts
  frontend/src/App.tsx
  frontend/src/api/manager/approveRequest.ts
  frontend/src/api/manager/getPendingAssessments.ts
  frontend/src/api/manager/index.ts
  frontend/src/api/manager/manageAssessment.ts
  frontend/src/components/Avatar/styled.ts
  frontend/src/constants/ButtonLabels.ts
  frontend/src/constants/menuRoles.tsx
  frontend/src/constants/queryKeyConstants.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/test.ts
  frontend/src/enums/api.ts
  frontend/src/enums/sizes.ts
  frontend/src/icons/menuIcons/index.ts
  frontend/src/icons/menuIcons/pendingAssessments.svg
  frontend/src/pages/PassingTest/TestResult/ResultDescription/ResultDescription.tsx
  frontend/src/pages/PendingAssessments/PendingAssessments.tsx
  frontend/src/pages/PendingAssessments/PendingAssessmentsContainer.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtonsContainer.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/index.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/styled.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestItem.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/RequestTechnologies.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/TechnologyItem.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/TechnologyItemContainer.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/index.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/styled.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/index.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/styled.ts
  frontend/src/pages/PendingAssessments/RequestItem/index.ts
  frontend/src/pages/PendingAssessments/RequestItem/styled.ts
  frontend/src/pages/PendingAssessments/index.ts
  frontend/src/pages/PendingAssessments/styled.ts
  frontend/src/pages/PendingAssessments/types.ts
  frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/Requests/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/Requests.tsx
  frontend/src/pages/Requests/RequestsContainer.tsx
  frontend/src/pages/index.ts
  frontend/src/types/api.dto.ts
  frontend/src/types/course.ts
  frontend/src/types/request.ts
  frontend/src/types/skill.ts
  frontend/src/types/test.ts
Labels: feature

#463 Bugfix | V1-206 - Fixed content overflow for phone and skype column at Employee page
  frontend/src/components/TextTooltip/TextTooltip.tsx
  frontend/src/components/TextTooltip/index.ts
  frontend/src/components/TextTooltip/styled.ts
  frontend/src/components/TextTooltip/types.ts
  frontend/src/enums/employee.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/EmployeeContent.tsx
Labels: bug, bug-fix

#459 Feature/v1-216 | Updated edit validations
  backend/src/db/models/Course.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/utils/normaliser/materials.ts
  backend/src/utils/validation/courses/constants.ts
  backend/src/utils/validation/schemas/courses.ts
Labels: feature

#467 Bugfix | V1-232 - Added UI changes
  frontend/src/api/userInfo/index.ts
  frontend/src/api/userInfo/useReadNotifications.ts
  frontend/src/components/Course/CourseButtons/CourseButtons.tsx
  frontend/src/components/Course/CourseButtons/styled.ts
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/MobileLink/MobileLink.tsx
  frontend/src/components/MobileLink/MobileLinkContainer.tsx
  frontend/src/components/MobileLink/index.ts
  frontend/src/components/MobileLink/styled.ts
  frontend/src/components/MobileLink/types.ts
  frontend/src/components/NotificationsBar/NotificationsBar.tsx
  frontend/src/components/NotificationsBar/NotificationsBarContainer.tsx
  frontend/src/components/NotificationsBar/styled.ts
  frontend/src/components/NotificationsBar/types.ts
  frontend/src/components/UserProfile/UserInfo/UserInfoItem/styled.ts
  frontend/src/components/UserProfile/UserInfo/styled.ts
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/CoursesList/types.ts
  frontend/src/pages/DetailedCourse/SimilarCourses/SimilarCourses.tsx
  frontend/src/pages/DetailedCourse/SimilarCourses/styled.ts
Labels: bug, bug-fix

#466 Bugfix/v1-210 | Fixed exercise migrations.
  backend/migrations-backdev/add_exercise.js
  backend/migrations/add_exercise.js
Labels: bug

#470 Refactor | V1-207 - refactored styles for UserProfile
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/components/UserProfile/UserAvatar/styled.ts
  frontend/src/components/UserProfile/UserInfo/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/styled.ts
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: refactor

#472 Bugfix | V1-234 - Fixed problems with RoleRoutes
  frontend/src/components/Routes/RoleRoute.tsx
Labels: bug, bug-fix

#474 Bugfix/v1-208 | Fixed problems with integer values validations
  backend/src/utils/validation/schemas/courses.ts
Labels: bug-fix

#469 Bugfix/v1-199 | Fixed no requests message and buttons loaders.
  frontend/src/pages/PendingAssessments/PendingAssessments.tsx
  frontend/src/pages/PendingAssessments/PendingAssessmentsContainer.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtonsContainer.tsx
  frontend/src/pages/PendingAssessments/types.ts
Labels: bug-fix

#477 Bug/v1-238 | Fixed unique techs issue and optional exercise validation.
  backend/src/db/models/Course.ts
  backend/src/utils/validation/courseModel.ts
  backend/src/utils/validation/schemas/courses.ts
Labels: bug-fix

#479 Feature/v1-219 | Implement scheduler for updating test statuses.
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/interfaces/common/scheduler.ts
  backend/src/middlewares/connectionMiddleware.ts
  backend/src/utils/connection/connectToDatabase.ts
  backend/src/utils/connection/index.ts
  backend/src/utils/date/testDate.ts
  backend/src/utils/schedule/common.ts
  backend/src/utils/schedule/constants.ts
  backend/src/utils/schedule/index.ts
  backend/src/utils/schedule/registerScheduler.ts
  backend/src/utils/schedule/schedulers/updateTestStatuses.ts
Labels: feature

#483 V1-202 Notification
  backend/src/controllers/manager/assignEmployeeCourses.ts
  backend/src/controllers/notifications/addNotification.ts
  backend/src/controllers/notifications/readNotifications.ts
  backend/src/enums/notificationEnums.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/routing/userRouter.ts
  backend/src/utils/notifications/convertCourseStatusToNotificationInfo.ts
Labels: bug, bug-fix

#484 V1-162/CourseEditor: definition and skill steps
  frontend/src/api/courses/getCourseInfo.ts
  frontend/src/components/EditorTabs/EditorTabs.tsx
  frontend/src/components/EditorTabs/types.ts
  frontend/src/constants/ButtonLabels.ts
  frontend/src/constants/courseEditor.ts
  frontend/src/pages/CourseEditor/ActionButtons/ActionButtons.tsx
  frontend/src/pages/CourseEditor/ActionButtons/index.ts
  frontend/src/pages/CourseEditor/ActionButtons/styled.ts
  frontend/src/pages/CourseEditor/CourseEditor.tsx
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/DefinitionStep.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/styled.ts
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStepContainer.tsx
  frontend/src/pages/CourseEditor/SkillsStep/index.ts
  frontend/src/pages/CourseEditor/SkillsStep/styled.ts
  frontend/src/pages/CourseEditor/styled.ts
  frontend/src/pages/CourseEditor/types.ts
  frontend/src/pages/CourseEditor/utils.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseActions/DetailedCourseActions.tsx
  frontend/src/pages/DetailedCourse/EditCourseButton/EditCourseButton.tsx
  frontend/src/pages/DetailedCourse/EditCourseButton/index.ts
  frontend/src/pages/DetailedCourse/EditCourseButton/styled.ts
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/DetailedCourse/types.ts
  frontend/src/themeSettings.ts
  frontend/src/types/course.ts
  frontend/src/types/skill.ts
  frontend/src/validations/courseEditorValidationSchema.tsx
Labels: feature

#485 Refactor | V1-240 - Refactored Routes structure. Deleted layout in components
  frontend/src/App.tsx
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/auth/types.ts
  frontend/src/api/logOut/useLogOut.tsx
  frontend/src/components/Layout/AuthorizedLayout/AuthorizedLayout.tsx
  frontend/src/components/Layout/AuthorizedLayout/AuthorizedLayoutContainer.tsx
  frontend/src/components/Layout/DefaultLayout/DefaultLayout.tsx
  frontend/src/components/Layout/DefaultLayout/index.ts
  frontend/src/components/Layout/index.ts
  frontend/src/components/Layout/types.ts
  frontend/src/components/PageTitle/PageTitle.tsx
  frontend/src/components/PageTitle/index.ts
  frontend/src/components/PageTitle/types.ts
  frontend/src/components/Routes/AnonymousRoute.tsx
  frontend/src/components/Routes/AuthRoute.tsx
  frontend/src/components/Routes/PrivateRoute.tsx
  frontend/src/components/Routes/RoleRoute.tsx
  frontend/src/components/Routes/index.ts
  frontend/src/components/Routes/types.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCourses.tsx
  frontend/src/pages/Employees/Employees.tsx
  frontend/src/pages/Help/Help.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/NotFound/NotFoundContainer.tsx
  frontend/src/pages/NotFound/index.ts
  frontend/src/pages/NotFound/styled.ts
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PendingAssessments/PendingAssessments.tsx
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Requests/Requests.tsx
  frontend/src/pages/Skills/Skills.tsx
  frontend/src/pages/SkillsMap/SkillsMap.tsx
  frontend/src/pages/index.ts
Labels: bug-fix, refactor

#475 Bug/v1-237 | Fixed validation bugs in create course API.
  backend/src/controllers/admin/editCourse.ts
  backend/src/controllers/admin/preparingCourseData.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/utils/validation/courses/checkCourseValidationResult.ts
  backend/src/utils/validation/courses/constants.ts
  backend/src/utils/validation/courses/index.ts
  backend/src/utils/validation/courses/isValidAvatar.ts
  backend/src/utils/validation/courses/isValidComplexity.ts
  backend/src/utils/validation/courses/isValidCourseData.ts
  backend/src/utils/validation/courses/validateAvatar.ts
  backend/src/utils/validation/courses/validateComplexity.ts
  backend/src/utils/validation/courses/validateCourseData.ts
  backend/src/utils/validation/courses/validateDescription.ts
  backend/src/utils/validation/courses/validateMaterials.ts
  backend/src/utils/validation/courses/validateTechnologies.ts
  backend/src/utils/validation/courses/validateTest.ts
  backend/src/utils/validation/courses/validateTitle.ts
  backend/src/utils/validation/schemas/courses.ts
Labels: bug-fix

#487 Bugfix | V1-239, V1-233 - UI bugfixes
  frontend/public/index.html
  frontend/src/components/Course/CourseButtons/styled.ts
  frontend/src/components/Course/styled.ts
  frontend/src/components/TextTooltip/TextTooltip.tsx
  frontend/src/components/TextTooltip/index.ts
  frontend/src/components/TextTooltip/styled.ts
  frontend/src/components/TextTooltip/types.ts
  frontend/src/components/Tooltip/Tooltip.tsx
  frontend/src/components/Tooltip/index.ts
  frontend/src/index.css
  frontend/src/pages/DetailedCourse/DetailedCourseInfo/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/CourseItem.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/CourseItemContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/types/index.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/styled.ts
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/EmployeeContent.tsx
  frontend/src/pages/Employees/EmployeesList/EmployeeContent/styled.ts
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/StageController/StageController.tsx
  frontend/src/pages/LearningCourse/types.ts
  frontend/src/pages/LearningCourse/utils/getIsNextStageCompleted.ts
  frontend/src/pages/LearningCourse/utils/index.ts
  frontend/src/pages/LearningCourse/utils/types.ts
  frontend/src/pages/Requests/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/RequestItem/styled.ts
  frontend/src/themeSettings.ts
  frontend/src/utils/cache/getUserProfileCache.ts
  frontend/src/utils/helpers/convertToFullName.ts
Labels: bug-fix

#488 Feature/V1-250 | Implemented get test admin API.
  backend/src/controllers/admin/getTest.ts
  backend/src/db/providers/testProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/requests/tests/getTest.d.ts
  backend/src/routing/routes.ts
  backend/src/routing/testsRouter.ts
Labels: feature

#489 Bugfix | V1-242 - Fixed problem with not scrolling side mobile menu
  frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
Labels: bug, bug-fix

#491 Refactor | V1-236 - Refactored Layout at Assesments page
  frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/Requests/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/RequestItem/styled.ts
Labels: refactor

#495 Feature/v1-252 | API for edit course stepper
  backend/src/controllers/admin/getEditCoursePayload/getEditCoursePayload.ts
  backend/src/controllers/admin/getEditCoursePayload/utils/mappers.ts
  backend/src/controllers/admin/index.ts
  backend/src/db/models/Course.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/requests/admin/getEditCoursePayload.d.ts
  backend/src/routing/coursesRouter.ts
Labels: feature

#494 Bugfix | V1-239 - UI changes
  frontend/src/App.tsx
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/logOut/useLogOut.tsx
  frontend/src/components/Layout/AuthorizedLayout/AuthorizedLayoutContainer.tsx
  frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/SearchCourses.tsx
  frontend/src/components/Layout/AuthorizedLayout/Menu/Badge/utils.ts
  frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
  frontend/src/components/Layout/styled.ts
  frontend/src/components/NotificationsBar/NotificationsBar.tsx
  frontend/src/components/ScrollToTop/ScrollToTop.tsx
  frontend/src/components/ScrollToTop/index.ts
  frontend/src/components/SkillGroup/SkillItem/SkillItem.tsx
  frontend/src/components/SkillGroup/SkillItem/SkillItemContainer.tsx
  frontend/src/components/SkillGroup/SkillItem/index.ts
  frontend/src/components/SkillGroup/SkillItem/styled.ts
  frontend/src/components/Tooltip/Tooltip.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeSkillsAndCourses.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/styled.ts
  frontend/src/pages/PassingTest/TestResult/ResultDescription/ResultDescription.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/TechnologyItem.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/TechnologyItemContainer.tsx
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/index.ts
  frontend/src/pages/PendingAssessments/RequestItem/RequestTechnologies/TechnologyItem/styled.ts
  frontend/src/pages/PendingAssessments/types.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfo/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfo/index.ts
  frontend/src/pages/Profile/UserSkills/SkillInfo/styled.ts
  frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/index.ts
  frontend/src/pages/Profile/UserSkills/styled.ts
  frontend/src/pages/Profile/types.ts
  frontend/src/pages/Profile/utils/calculateSkillProgress.ts
  frontend/src/pages/Profile/utils/index.ts
  frontend/src/utils/helpers/convertCourseStatusToProgress.ts
Labels: bug, bug-fix

#482 Test configuration backend
  backend/.gitignore
  backend/.husky/pre-commit
  backend/babel.config.js
  backend/globalConfig.json
  backend/jest.config.js
  backend/migrations/20220125143932-init_collections.js
  backend/package-lock.json
  backend/package.json
  backend/src/__mock__/mockedCourses.ts
  backend/src/__tests__/api/applyCourse.test.ts
  backend/src/__tests__/api/auth.test.ts
  backend/src/__tests__/api/clientCourses.test.ts
  backend/src/__tests__/api/commonCourses.test.ts
  backend/src/__tests__/classes/classes.test.ts
  backend/src/__tests__/database/database.test.ts
  backend/src/__tests__/enviromentVars/env.test.ts
  backend/src/__tests__/utils/comparators.test.ts
  backend/src/__tests__/utils/date.test.ts
  backend/src/__tests__/utils/decode.test.ts
  backend/src/__tests__/utils/dto.test.ts
  backend/src/__tests__/utils/normalizers/agregation.test.ts
  backend/src/__tests__/utils/normalizers/courses.test.ts
  backend/src/app.ts
  backend/src/config/constants.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/tests/getTestResult.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/notificationProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/ISkill.ts
  backend/src/interfaces/Ientities/ISkillGroup.ts
  backend/src/interfaces/Ientities/IStackMember.ts
  backend/src/interfaces/Ientities/IUserSkill.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Imaterials.ts
  backend/src/interfaces/Ientities/Itest.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/interfaces/requests/auth/login.d.ts
  backend/src/interfaces/requests/common/payloads.d.ts
  backend/src/interfaces/requests/user/getProfileInfo.d.ts
  backend/src/server.ts
  backend/src/utils/comparator/ObjectId/compareObjectIds.ts
  backend/src/utils/comparator/ObjectId/containsObjectId.ts
  backend/src/utils/connection/connectToDatabase.ts
  backend/src/utils/normaliser/courseTest.ts
  backend/src/utils/normaliser/courseTests.ts
  backend/src/utils/normaliser/courses.ts
  backend/src/utils/skillsUtils.ts
  backend/src/utils/validation/schemas/courses.ts
  backend/tsconfig.json
Labels: improvement

#498 Bugfix | V1-241 - Fixed scrolling NavMenu on mobiles
  frontend/src/components/Layout/AuthorizedLayout/Menu/styled.ts
  frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
Labels: bug, bug-fix
