Repository k-krasilnikova/SUL, pull requests merged in 2022-06, with the labels that each got.

#511 Feature/v1-257 | BE code style empty lines.
  backend/src/controllers/admin/deleteCourse/deleteCourse.ts
  backend/src/controllers/admin/editCourse/editCourse.ts
  backend/src/controllers/auth/login/login.ts
  backend/src/controllers/auth/logout/logout.ts
  backend/src/controllers/auth/refresh/refresh.ts
  backend/src/controllers/clientCourses/applyCourse/applyCourse.ts
  backend/src/controllers/clientCourses/getClientCourse/getClientCourse.ts
  backend/src/controllers/clientCourses/passCourse/passCourse.ts
  backend/src/controllers/clientCourses/startCourse/startCourse.ts
  backend/src/controllers/courses/getMaterials/getMaterials.ts
  backend/src/controllers/manager/assignEmployeeCourses/assignEmployeeCourses.ts
  backend/src/controllers/manager/getEmployeeAvailableCourses/getEmployeeAvailableCourses.ts
  backend/src/controllers/manager/getEmployeeInfo/getEmployeeInfo.ts
  backend/src/controllers/manager/getPendingAssessments/getPendingAssessments.ts
  backend/src/controllers/notifications/readNotifications/readNotifications.ts
  backend/src/controllers/pendingCourses/approvePendingCourse/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse/declinePendingCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses/getPendingCourses.ts
  backend/src/controllers/pendingCourses/updatePendingCourse/updatePendingCourse.ts
  backend/src/controllers/skills/getAllSkills/getAllSkills.ts
  backend/src/controllers/tests/getTest/getTest.ts
  backend/src/controllers/tests/getTestResult/getTestResult.ts
  backend/src/controllers/tests/getTestTime/getTestTime.ts
  backend/src/controllers/tests/passTest/passTest.ts
  backend/src/controllers/tests/sendTestResults/sendTestResults.ts
  backend/src/controllers/tests/startTest/startTest.ts
  backend/src/controllers/user/getProfileInfo/getProfileInfo.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/date/testDate.ts
  backend/src/utils/decode/decodeSearchParams.ts
  backend/src/utils/dto/dtoUtils.ts
  backend/src/utils/normaliser/employees.ts
  backend/src/utils/skillsUtils.ts
  backend/src/utils/typeConversion/datetime/datetimeTypeConversions.ts
  backend/src/utils/typeGuards/isExpectedHttpError.ts
Labels: feature, improvement

#505 Bug/v1-158 | Fixed search by skills name & display long skill name
  backend/src/controllers/skills/getAllSkills/getAllSkills.ts
  backend/src/db/providers/skillProvider.ts
  frontend/src/components/SkillGroup/SkillItem/styled.ts
  frontend/src/pages/Skills/SkillsContainer.tsx
Labels: bug

#513 Feature/v1-245 - refactor return's types
  backend/src/__tests__/database/database.test.ts
  backend/src/controllers/clientCourses/getClientCourse/utils/mappers.ts
  backend/src/controllers/courses/getCourse/utils/mappers.ts
  backend/src/controllers/notifications/addNotification/utils/converters.ts
  backend/src/controllers/pendingCourses/getPendingCourses/getPendingCourses.ts
  backend/src/controllers/tests/passTest/utils/helpers.ts
  backend/src/db/models/AccessTokens.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/notificationProvider.ts
  backend/src/db/providers/pendingCoursesProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Iauth/authInterfaces.ts
  backend/src/interfaces/Ientities/IUserSkill.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/interfaces/dto/initial.ts
  backend/src/interfaces/requests/courses/getMaterials.d.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/combineFullName.ts
  backend/src/utils/dto/dtoUtils.ts
  backend/src/utils/normaliser/aggregateNormalizer.ts
  backend/src/utils/normaliser/prepareSimilarCourses.ts
  backend/src/utils/skillsUtils.ts
  backend/src/utils/validation/checkTestDate.ts
  backend/src/utils/validation/strings/isNotNumberOnly.ts
  backend/src/utils/validation/strings/isNotSpecialsOnly.ts
Labels: improvement

#514 Improvement | Added utils tests to BE.
  backend/src/__tests__/utils/auth.test.ts
  backend/src/__tests__/utils/converters/dateTime.test.ts
  backend/src/__tests__/utils/strings.test.ts
  backend/src/__tests__/utils/typeGuards.test.ts
Labels: improvement

#519 Improvement | Added tests for validations [BE]
  backend/src/__tests__/utils/validations/course.test.ts
  backend/src/utils/hash/.gitignore
  backend/src/utils/parsers/.gitignore
Labels: improvement

#496 Feature/v1-247 | Removed API adapters.
  backend/src/__tests__/api/applyCourse.test.ts
  backend/src/__tests__/api/auth.test.ts
  backend/src/__tests__/api/clientCourses.test.ts
  backend/src/controllers/admin/addCourse/addCourse.ts
  backend/src/controllers/admin/editCourse/editCourse.ts
  backend/src/controllers/clientCourses/adapterClientCourse.ts
  backend/src/controllers/clientCourses/applyCourse/applyCourse.ts
  backend/src/controllers/clientCourses/manageAssessment/manageAssessment.ts
  backend/src/controllers/courses/getCoursesMap/getCoursesMap.ts
  backend/src/controllers/manager/adapterManager.ts
  backend/src/controllers/manager/assignEmployeeCourses/assignEmployeeCourses.ts
  backend/src/controllers/manager/getEmployeeAvailableCourses/getEmployeeAvailableCourses.ts
  backend/src/controllers/manager/getPendingAssessments/getPendingAssessments.ts
  backend/src/controllers/notifications/addNotification/addNotification.ts
  backend/src/controllers/pendingCourses/adapterSender.ts
  backend/src/controllers/pendingCourses/approvePendingCourse/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse/declinePendingCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses/getPendingCourses.ts
  backend/src/controllers/pendingCourses/index.ts
  backend/src/controllers/pendingCourses/updatePendingCourse/updatePendingCourse.ts
  backend/src/controllers/tests/getAchievements/getAchievements.ts
  backend/src/controllers/tests/getTestResult/getTestResult.ts
  backend/src/controllers/tests/passTest/passTest.ts
  backend/src/controllers/tests/sendTestResults/sendTestResults.ts
  backend/src/controllers/user/adapterUser.ts
  backend/src/interfaces/requests/admin/addCourse.d.ts
  backend/src/interfaces/requests/admin/editCourse.d.ts
  backend/src/interfaces/requests/clientCourses/applyCourse.d.ts
  backend/src/interfaces/requests/clientCourses/manageAssessment.d.ts
  backend/src/interfaces/requests/common/locals.d.ts
  backend/src/interfaces/requests/common/payloads.d.ts
  backend/src/interfaces/requests/courses/getCoursesMap.d.ts
  backend/src/interfaces/requests/manager/assignEmployeeCourses.d.ts
  backend/src/interfaces/requests/manager/getEmployeeAvailableCourses.d.ts
  backend/src/interfaces/requests/manager/getPendingAssessments.d.ts
  backend/src/interfaces/requests/notifications/addNotification.d.ts
  backend/src/interfaces/requests/pendingCourses/approvePendingCourse.d.ts
  backend/src/interfaces/requests/pendingCourses/declinePendingCourse.d.ts
  backend/src/interfaces/requests/tests/getTestResult.d.ts
  backend/src/interfaces/requests/tests/passTest.d.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/utils/skillsUtils.ts
  frontend/src/api/courses/applyCourse.ts
  frontend/src/api/manager/approveRequest.ts
  frontend/src/api/manager/declineRequest.ts
  frontend/src/api/test/sendTestResult.ts
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/Requests/RequestsContainer.tsx
  frontend/src/types/api.dto.ts
Labels: feature, improvement

#518 feature/248 - remove unnecessary objects in response
  backend/src/controllers/clientCourses/startCourse/startCourse.ts
  backend/src/interfaces/requests/clientCourses/startCourse.d.ts
Labels: improvement

#508 refactor: imports controllers, middlewares, errors
  backend/migrations-backdev/20220125143932-backdev_col.js
  backend/src/__tests__/api/applyCourse.test.ts
  backend/src/__tests__/api/clientCourses.test.ts
  backend/src/__tests__/classes/classes.test.ts
  backend/src/app.ts
  backend/src/classes/errors/clientErrors/index.ts
  backend/src/classes/errors/common/index.ts
  backend/src/classes/errors/serverErrors/index.ts
  backend/src/controllers/admin/deleteCourse/deleteCourse.ts
  backend/src/controllers/admin/editCourse/editCourse.ts
  backend/src/controllers/auth/login/login.ts
  backend/src/controllers/auth/refresh/refresh.ts
  backend/src/controllers/clientCourses/applyCourse/applyCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses/getAllClientCourses.ts
  backend/src/controllers/clientCourses/manageAssessment/manageAssessment.ts
  backend/src/controllers/clientCourses/passCourse/passCourse.ts
  backend/src/controllers/clientCourses/startCourse/startCourse.ts
  backend/src/controllers/courses/getCourseById.ts
  backend/src/controllers/manager/assignEmployeeCourses/assignEmployeeCourses.ts
  backend/src/controllers/manager/getEmployeeAvailableCourses/getEmployeeAvailableCourses.ts
  backend/src/controllers/pendingCourses/approvePendingCourse/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse/declinePendingCourse.ts
  backend/src/controllers/tests/getTest/getTest.ts
  backend/src/controllers/tests/getTestResult/getTestResult.ts
  backend/src/controllers/tests/getTestTime/getTestTime.ts
  backend/src/controllers/tests/index.ts
  backend/src/controllers/tests/passTest/passTest.ts
  backend/src/controllers/tests/sendTestResults/sendTestResults.ts
  backend/src/controllers/tests/startTest/startTest.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/notificationProvider.ts
  backend/src/db/providers/pendingCoursesProvider.ts
  backend/src/db/providers/skillProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/middlewares/connectionMiddleware.ts
  backend/src/middlewares/errorHandlingMiddleware.ts
  backend/src/middlewares/handleInternalErrorMiddleware.ts
  backend/src/middlewares/index.ts
  backend/src/middlewares/sendMail.ts
  backend/src/middlewares/withAuth.ts
  backend/src/routing/accountRouter.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/routing/skillsRouter.ts
  backend/src/routing/testsRouter.ts
  backend/src/routing/userRouter.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/validation/courses/checkCourseValidationResult.ts
Labels: improvement

#526 bug/v1-158 | Hide long skill name with dots displaying
  frontend/src/pages/Skills/SkillGroup/SkillItem/SkillItem.tsx
  frontend/src/pages/Skills/SkillGroup/SkillItem/styled.ts
  frontend/src/pages/Skills/utils.ts
Labels: bug

#524 Feature/v1-214 Validation for Course Editor
  frontend/src/constants/courseEditor.ts
  frontend/src/enums/materials.ts
  frontend/src/pages/CourseEditor/CourseEditor.tsx
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/DefinitionStep.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/styled.ts
  frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
  frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/QuestionItem.tsx
  frontend/src/pages/CourseEditor/TestStep/TestStep.tsx
  frontend/src/pages/CourseEditor/TestStep/styled.ts
  frontend/src/pages/CourseEditor/types.ts
  frontend/src/pages/CourseEditor/utils.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/CourseItem.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/utils/helpers/setFirstLetterUppercase.ts
  frontend/src/utils/helpers/strings/capitalizeFirstLetter.ts
  frontend/src/utils/helpers/strings/index.ts
  frontend/src/validations/courseEditorValidationSchema.tsx
  frontend/src/validations/index.ts
  frontend/src/validations/schemas/courseEditorValidationSchema.ts
  frontend/src/validations/schemas/index.ts
  frontend/src/validations/schemas/signInValidationSchema.ts
  frontend/src/validations/utils/index.ts
  frontend/src/validations/utils/isNotNumberOnly.ts
  frontend/src/validations/utils/isNotSpecialsOnly.ts
Labels: feature

#516 Improvement/V1-249 - refactored some errors messages
  backend/src/__mock__/mockedCourses.ts
  backend/src/controllers/admin/deleteCourse/deleteCourse.ts
  backend/src/controllers/auth/refresh/refresh.ts
  backend/src/controllers/clientCourses/applyCourse/applyCourse.ts
  backend/src/controllers/clientCourses/passCourse/passCourse.ts
  backend/src/controllers/pendingCourses/approvePendingCourse/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse/declinePendingCourse.ts
  backend/src/controllers/tests/getTest/getTest.ts
  backend/src/controllers/tests/getTestTime/getTestTime.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/middlewares/sendMail.ts
Labels: improvement

#529 UI Fixes | V1-253 - Fixed UI
  frontend/src/components/Button/ButtonVariants/styled.ts
  frontend/src/components/Course/CourseInfo/styled.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/ActionButtons.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/ActionButtonsContainer.tsx
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/styled.ts
  frontend/src/pages/EmployeeProfile/types.ts
Labels: bug-fix

#531 V1-202 - fixed long title overflow
  frontend/src/components/NotificationsBar/NotificationPlate/styled.tsx
Labels: bug, bug-fix

#534 Bugfix | V1-241 Fixed mobile menu after conversation
  frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
Labels: bug-fix

#536 Fix | V1-263 - Fixed Action Buttons at Pending Request page
  frontend/src/api/manager/approveRequest.ts
  frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
  frontend/src/pages/Requests/RequestItem/RequestItem.tsx
  frontend/src/pages/Requests/Requests.tsx
  frontend/src/pages/Requests/RequestsContainer.tsx
  frontend/src/pages/Requests/types.ts
  frontend/src/types/api.dto.ts
Labels: bug-fix

#539 V1-214 Bugfix: fixed validation
  frontend/src/components/EditorTabs/ActionButtons/ActionButtons.tsx
  frontend/src/constants/courseEditor.ts
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
  frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/QuestionItem.tsx
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/styled.ts
  frontend/src/pages/CourseEditor/TestStep/TestStep.tsx
  frontend/src/pages/CourseEditor/types.ts
  frontend/src/validations/schemas/courseEditorValidationSchema.ts
Labels: bug, bug-fix

#544 Fix/v1-264 | Fixed plain material blank page issue.
  frontend/src/enums/materials.ts
Labels: bug

#545 Bug-fix and feature/262 - refactor search
  backend/jest.config.js
  backend/src/controllers/clientCourses/getClientCourse/getClientCourse.ts
  backend/src/db/providers/clientCourseProvider.ts
  frontend/src/api/courses/searchAllCourses.ts
  frontend/src/api/myCourses/getClientCourseInfo.ts
  frontend/src/components/Course/CourseInfo/styled.ts
  frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/SearchCourses.tsx
  frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/styled.ts
  frontend/src/components/Layout/AuthorizedLayout/Header/styled.ts
  frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
  frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
  frontend/src/components/Layout/MobileSearch/index.ts
  frontend/src/components/Layout/MobileSearch/styled.ts
  frontend/src/components/Layout/components/SearchResult/SearchResult.tsx
  frontend/src/components/Layout/components/SearchResult/SearchResultContainer.tsx
  frontend/src/components/Layout/components/SearchResult/SearchResultItem/SearchResultItemContainer.tsx
  frontend/src/components/Layout/components/SearchResult/index.ts
  frontend/src/components/Layout/components/SearchResult/styled.ts
  frontend/src/components/Layout/components/types.ts
  frontend/src/components/Layout/index.ts
  frontend/src/components/Routes/AuthRoute.tsx
  frontend/src/hooks/useToggle.tsx
  frontend/src/icons/searchIcon.svg
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
Labels: bug-fix, improvement

#546 bug/Fixed Skill components for admin
  frontend/src/pages/Skills/SkillGroup/SkillGroup.tsx
  frontend/src/pages/Skills/SkillGroup/styled.ts
  frontend/src/pages/Skills/styled.ts
  frontend/src/pages/Skills/utils.ts
Labels: bug

#547 Bugfix/V1-260 | Fixed scheduler time diapasons and status checks.
  backend/src/utils/schedule/updateTestStatuses.ts
Labels: bug-fix

#548 V1-162/Feature: Course editor additional functionality
  frontend/src/components/EditorTabs/EditorTabsContainer.tsx
  frontend/src/components/EditorTabs/types.ts
  frontend/src/constants/courseEditor.ts
  frontend/src/pages/CourseCreator/CourseCreator.tsx
  frontend/src/pages/CourseCreator/CourseCreatorContainer.tsx
  frontend/src/pages/CourseCreator/types.ts
  frontend/src/pages/CourseEditor/CourseEditor.tsx
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/DefinitionStep.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/styled.ts
  frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
  frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
  frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/styled.ts
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/QuestionItem.tsx
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/styled.ts
  frontend/src/pages/CourseEditor/TestStep/TestStep.tsx
  frontend/src/pages/CourseEditor/styled.ts
  frontend/src/pages/CourseEditor/types.ts
  frontend/src/pages/CourseEditor/utils.ts
  frontend/src/pages/DetailedCourse/EditCourseButton/styled.ts
  frontend/src/pages/DetailedCourse/styled.ts
Labels: feature, improvement

#550 Fixes | V1-263 - UI issues
  frontend/src/App.tsx
  frontend/src/api/admin/editCourseData.ts
  frontend/src/api/courses/applyCourse.ts
  frontend/src/api/courses/deleteCourse.ts
  frontend/src/api/manager/approveRequest.ts
  frontend/src/api/manager/declineRequest.ts
  frontend/src/components/CoursesFilter/CoursesFilter.tsx
  frontend/src/components/CoursesFilter/CoursesFilterContainer.tsx
  frontend/src/components/CoursesFilter/FiltersTags/FiltersTags.tsx
  frontend/src/components/CoursesFilter/FiltersTags/styled.ts
  frontend/src/components/CoursesFilter/components/CustomCheckbox/styled.ts
  frontend/src/components/CoursesFilter/components/CustomSelect/CustomSelect.tsx
  frontend/src/components/CoursesFilter/components/CustomSelect/styled.ts
  frontend/src/components/CoursesFilter/styled.ts
  frontend/src/components/CoursesFilter/types.ts
  frontend/src/components/CoursesFiltersContextProvider/CoursesFiltersContextProvider.tsx
  frontend/src/components/CoursesFiltersContextProvider/index.ts
  frontend/src/components/CustomNavLink/CustomNavLink.tsx
  frontend/src/components/CustomNavLink/CustomNavLinkContainer.tsx
  frontend/src/components/CustomNavLink/index.ts
  frontend/src/components/Routes/AuthRoute.tsx
  frontend/src/context/CoursesFiltersContext.tsx
  frontend/src/context/index.ts
  frontend/src/context/types.ts
  frontend/src/enums/coursesFilters.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useGetCoursesPaths.tsx
  frontend/src/hooks/useSetCoursesFiltersContext.tsx
  frontend/src/pages/CourseCreator/CourseCreator.tsx
  frontend/src/pages/CourseCreator/CourseCreatorContainer.tsx
  frontend/src/pages/CourseCreator/types.ts
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseInfo/styled.ts
  frontend/src/pages/DetailedCourse/components/BackButton/BackButton.tsx
  frontend/src/pages/DetailedCourse/components/BackButton/BackButtonContainer.tsx
  frontend/src/pages/DetailedCourse/components/BackButton/index.ts
  frontend/src/pages/DetailedCourse/types.ts
  frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/CoursesList/CoursesList.tsx
  frontend/src/pages/Employees/EmployeesList/styled.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/types.ts
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/themeSettings.ts
Labels: feature, bug-fix

#553 fix bug with disabled test
  frontend/package-lock.json
  frontend/src/components/Dialogs/StartTestDialog/withStartTest.tsx
Labels: bug-fix

#555 UI fixes at LearningCourse page
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/Material/Material.tsx
  frontend/src/pages/LearningCourse/Material/styled.ts
  frontend/src/pages/LearningCourse/StageController/styled.ts
Labels: bug-fix

#556 Fixed issue with successful passing test
  backend/src/controllers/tests/getAchievements/getAchievements.ts
  backend/src/db/providers/courseProvider.ts
Labels: bug

#563 V1-271 - fixed notification text and order
  backend/src/controllers/manager/assignEmployeeCourses/assignEmployeeCourses.ts
  backend/src/db/providers/notificationProvider.ts
  backend/src/enums/notification.ts
Labels: bug, bug-fix

#564 Bugfix | V1-271 Fixed notifications and search in header
  frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/SearchCoursesContainer.tsx
  frontend/src/components/NotificationsBar/NotificationsBarContainer.tsx
Labels: bug, bug-fix

#562 Bugfix/v1-269 Issues with creator and editor
  frontend/src/components/EditorTabs/ActionButtons/ActionButtons.tsx
  frontend/src/components/EditorTabs/EditorTabs.tsx
  frontend/src/components/EditorTabs/EditorTabsContainer.tsx
  frontend/src/components/EditorTabs/types.ts
  frontend/src/constants/courseEditor.ts
  frontend/src/constants/routes.ts
  frontend/src/pages/CourseCreator/CourseCreator.tsx
  frontend/src/pages/CourseCreator/CourseCreatorContainer.tsx
  frontend/src/pages/CourseCreator/types.ts
  frontend/src/pages/CourseCreator/utils.ts
  frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/DefinitionStep.tsx
  frontend/src/pages/CourseEditor/DefinitionStep/styled.ts
  frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
  frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
  frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
  frontend/src/pages/CourseEditor/TestStep/QuestionItem/QuestionItem.tsx
  frontend/src/pages/CourseEditor/TestStep/TestStep.tsx
  frontend/src/pages/CourseEditor/TestStep/styled.ts
  frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploader.tsx
  frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploaderContainer.tsx
  frontend/src/pages/CourseEditor/components/ImagesUploader/styled.ts
  frontend/src/pages/CourseEditor/types.ts
  frontend/src/pages/CourseEditor/utils.ts
  frontend/src/pages/CoursesList/AddCourseButton/styled.ts
  frontend/src/types/test.ts
  frontend/src/validations/schemas/courseEditorValidationSchema.ts
Labels: feature, bug-fix

#566 Fixed error messages for uploader at Course Creator/Editor
  frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploader.tsx
  frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploaderContainer.tsx
Labels: hot-fix
