Repository k-krasilnikova/SUL, pull requests merged in 2022-01, with the labels that each got.

#30 feature/v1-022: add course schema and materials
  backend/package.json
  backend/src/db/models/Course.ts
  backend/src/db/models/Materials.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/authProvider.ts
  backend/src/interfaces/entities/Icourses.ts
  backend/src/interfaces/entities/Imaterials.ts
  backend/src/interfaces/entities/Iusers.ts
  backend/src/modules/auth/authController.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/dto/dtoUtils.ts
Labels: feature

#27 feature/v1-030
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/profile/getProfile.ts
  frontend/src/components/Avatar/Avatar.tsx
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/CourseInfo.tsx
  frontend/src/components/Course/index.ts
  frontend/src/components/Course/styled.ts
  frontend/src/components/Image/Image.tsx
  frontend/src/components/Image/index.ts
  frontend/src/components/Image/styled.tsx
  frontend/src/components/layout/Header/Header.tsx
  frontend/src/components/layout/UserDropDown/UserDropDown.tsx
  frontend/src/components/layout/UserDropDown/UserDropDownContainer.tsx
  frontend/src/constants/sizes.ts
  frontend/src/icons/imageDefault.png
  frontend/src/icons/index.ts
  frontend/src/pages/MyCourses/MyCourses.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/ProfileContainer.tsx
  frontend/src/types/user.ts
Labels: feature

#33 Feature/V1-031 feat: implement PDFViewer and Help page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/PDFViewerContainer.tsx
  frontend/src/components/PDFViewer/index.tsx
  frontend/src/components/PDFViewer/styled.js
  frontend/src/constants/pdfViewer.ts
  frontend/src/docs/sul.pdf
  frontend/src/pages/Help/Help.tsx
  frontend/src/types/global.d.ts
  frontend/tsconfig.json
Labels: feature

#46 V1-014 feat: implement menu according to the role
  frontend/src/api/profile/getProfile.ts
  frontend/src/components/Layout/Menu/Menu.tsx
  frontend/src/components/Layout/Menu/MenuContainer.tsx
  frontend/src/constants/menuRoles.tsx
  frontend/src/types/menu.ts
Labels: feature

#47 feature/v1-051/common No Content component
  frontend/src/components/NoContent/NoContent.tsx
  frontend/src/components/NoContent/index.ts
  frontend/src/components/NoContent/styled.ts
  frontend/src/constants/messages.tsx
  frontend/src/pages/MyCourses/MyCourses.tsx
Labels: feature

#48 bugfix/V1-031: implement correct PDFViewer working
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/PDFViewerContainer.tsx
  frontend/src/components/PDFViewer/styled.js
Labels: bug-fix

#45 Feature/025-part 2 : refactor code
  backend/.eslintrc.json
  backend/migrations/20220104154539-courses_migration.js
  backend/package-lock.json
  backend/src/app.ts
  backend/src/config/constants.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/auth/refresh.ts
  backend/src/controllers/courses/getAllCourses.ts
  backend/src/controllers/materials/getAllMaterials.ts
  backend/src/controllers/materials/getMaterial.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/models/Course.ts
  backend/src/db/models/Materials.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/materialProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/IMaterials/IQueryMaterials.ts
  backend/src/interfaces/Iauth/authInterfaces.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Imaterials.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/materialsRouter.ts
  backend/src/routing/routes.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/dto/dtoUtils.ts
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/auth/getAuth.tsx
  frontend/src/api/courses/getCourses.ts
  frontend/src/api/courses/index.ts
  frontend/src/components/Avatar/Avatar.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Image/Image.tsx
  frontend/src/components/Image/styled.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Menu/Menu.tsx
  frontend/src/components/Layout/UserDropDown/UserDropDown.tsx
  frontend/src/components/Layout/UserDropDown/UserDropDownContainer.tsx
  frontend/src/components/PDFViewer/PDFViewerContainer.tsx
  frontend/src/constants/authConstants.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/MyCourses/MyCourses.tsx
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/utils/helpers/getAuthResponseData.tsx
  frontend/src/utils/helpers/getUserIdCookie.tsx
  frontend/tsconfig.json
Labels: feature

#49 Feature/V1-050 Implement NotFound page
  frontend/src/App.tsx
  frontend/src/components/NoContent/styled.ts
  frontend/src/components/PDFViewer/styled.js
  frontend/src/constants/routes.ts
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/NotFound/index.ts
  frontend/src/pages/NotFound/styled.ts
  frontend/src/pages/index.ts
Labels: feature

#52 Fixed: No Content displayed in center
  frontend/src/components/Layout/Menu/styled.ts
Labels: bug-fix

#54 V1-031 bugfix: fixed PDF Viewer buttons position
  frontend/src/components/PDFViewer/styled.js
Labels: bug-fix

#53 feature/v1-052/top bar changed
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Header/MyCoursesCounter/MyCoursesCounter.tsx
  frontend/src/components/Layout/Header/MyCoursesCounter/index.ts
  frontend/src/components/Layout/Header/index.ts
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/components/Layout/UserDropDown/UserDropDown.tsx
  frontend/src/components/Layout/UserDropDown/UserDropDownContainer.tsx
  frontend/src/components/Layout/UserDropDown/index.ts
  frontend/src/components/Layout/UserDropDown/styled.ts
  frontend/src/components/Layout/styled.ts
  frontend/src/icons/alert.svg
  frontend/src/icons/filter.svg
  frontend/src/icons/index.ts
  frontend/src/icons/logOut.svg
  frontend/src/pages/Profile/Profile.tsx
Labels: feature

#55 feature/v1-056/favicon added
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: feature

#56 V1-055 feat: implement safe route for Sign In page
  frontend/src/App.tsx
  frontend/src/components/AnonymousRoute/AnonymousRoute.tsx
Labels: feature

#58 bugfix/v1-030/my courses changed
  backend/package.json
  frontend/src/pages/MyCourses/MyCourses.tsx
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/index.ts
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#61 bugfix/v1-052/topbar
  backend/package-lock.json
  backend/package.json
  frontend/.eslintrc.json
  frontend/src/api/myCourses/getMyCourses.ts
  frontend/src/api/userInfo/getUserInfo.ts
  frontend/src/api/userInfo/index.ts
  frontend/src/components/BrandLogo/BrandLogo.tsx
  frontend/src/components/BrandLogo/index.ts
  frontend/src/components/BrandLogo/styled.ts
  frontend/src/components/Layout/AuthorizedLayoutContainer.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/index.ts
  frontend/src/pages/Profile/Profile.tsx
Labels: bug-fix

#60 feature-033: get course info by stage
  backend/migrations/20211219190858-init_collections.js
  backend/src/config/constants.ts
  backend/src/controllers/courses/applyCourse.ts
  backend/src/controllers/materials/getAllMaterials.ts
  backend/src/controllers/materials/getMaterials.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/models/Course.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/materialProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/materialsRouter.ts
  backend/src/routing/routes.ts
  backend/src/utils/dto/dtoUtils.ts
Labels: feature

#62 bugfix/v1-063/get my courses API changed
  frontend/src/api/myCourses/getMyCourses.ts
Labels: bug-fix

#43 feature/v1 045 - new profile page
  frontend/src/api/profile/getProfile.ts
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/NoContent/NoContent.tsx
  frontend/src/components/NoContent/styled.ts
  frontend/src/constants/coursesList.ts
  frontend/src/constants/coursesList.tsx
  frontend/src/constants/messages.ts
  frontend/src/constants/skills.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/ProfileContainer.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/UserSkillsContainer.tsx
  frontend/src/pages/Profile/UserSkills/index.ts
  frontend/src/pages/Profile/UserSkills/styled.ts
  frontend/src/pages/Profile/styled.ts
  frontend/src/types/course.ts
  frontend/src/types/serverError.ts
  frontend/src/types/user.ts
  frontend/src/utils/helpers/isCourseCompleted.ts
Labels: feature, required-changes

#71 V1-050 feat: implement correct Not Found page displaying for unauthorised users
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/NotFound/NotFoundContainer.tsx
  frontend/src/pages/NotFound/index.ts
  frontend/src/pages/NotFound/styled.ts
Labels: feature

#70 Feature/057 - add pass course endpoints
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/controllers/clientCourses/getClientCourse.ts
  backend/src/controllers/clientCourses/passCourse.ts
  backend/src/controllers/clientCourses/startCourse.ts
  backend/src/controllers/courses/getMaterials.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/materialProvider.ts
  backend/src/enums/coursesEnums.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
Labels: feature

#66 Feature/v1-028 Detailed course page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/courses/applyCourse.ts
  frontend/src/api/courses/getCourseInfo.ts
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/CourseInfo.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Image/styled.tsx
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/PDFViewer/styled.js
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/components/ProgressBar/index.ts
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/constants/detailedCourse.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/index.ts
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/index.ts
  frontend/src/types/responseData.ts
  frontend/tsconfig.json
Labels: feature

#79 [bugfix/feature/v1-064] Replaced fonts
  backend/src/db/providers/courseProvider.ts
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/themeSettings.ts
Labels: bug-fix

#80 V1-065 feat: implement lazy loading for pages
  frontend/src/App.tsx
  frontend/src/components/Loader/Loader.tsx
  frontend/src/components/Loader/index.ts
  frontend/src/components/Loader/styled.ts
  frontend/src/pages/index.ts
Labels: feature

#59 [feature/v1-054] Added new Sign in form style, response design
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/api/logOut/index.ts
  frontend/src/api/logOut/logOut.tsx
  frontend/src/components/Image/styled.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/components/TextField/styled.ts
  frontend/src/constants/routes.ts
  frontend/src/icons/index.ts
  frontend/src/icons/signInImage.jpeg
  frontend/src/index.css
  frontend/src/pages/SignIn/Definition/Definition.tsx
  frontend/src/pages/SignIn/Definition/styled.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/pages/SignIn/styled.tsx
  frontend/src/themeSettings.ts
  frontend/src/types/signIn.ts
  frontend/src/types/user.ts
  frontend/src/utils/helpers/isCourseCompleted.ts
  frontend/src/utils/helpers/logOutHandler.tsx
Labels: feature, required-changes

#83 V1-031 fix: fixed according to QA review
  frontend/package-lock.json
  frontend/src/components/PDFViewer/styled.js
  frontend/src/themeSettings.ts
Labels: bug-fix

#89 bug/v1-065/scrollbar for firefox
  frontend/src/index.css
Labels: bug-fix

#78 bugfix/057 - add error boundry
  backend/migrations/20211219190858-init_collections.js
  backend/src/app.ts
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/controllers/clientCourses/passCourse.ts
  backend/src/db/models/ClientCourses.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/interfaces/ICourses/IQueryCourses.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/utils/validation/.gitignore
  backend/src/utils/validation/checkDuplicates.ts
Labels: bug-fix

#91 Feature/v1-065 Lazy Loading
  frontend/src/App.tsx
  frontend/src/components/Avatar/index.ts
  frontend/src/components/Button/index.ts
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/index.ts
  frontend/src/components/Image/index.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/DefaultLayout.tsx
  frontend/src/components/Loader/Loader.tsx
  frontend/src/components/Loader/index.ts
  frontend/src/components/Loader/styled.ts
  frontend/src/components/NoContent/index.ts
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/index.tsx
  frontend/src/components/PDFViewer/styled.js
  frontend/src/components/ProgressBar/index.ts
  frontend/src/components/TextField/index.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/Help/Help.tsx
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/pages/Profile/Profile.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/index.ts
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/index.ts
Labels: feature

#93 bugfix/v1-030/style of my courses fixed
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/icons/imageDefault.png
  frontend/src/icons/image_default.svg
  frontend/src/icons/index.ts
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#95 bugfix/v1-035/Learning course style fixed
  frontend/src/components/Arrows/arrowBack.tsx
  frontend/src/components/Arrows/arrowForward.tsx
  frontend/src/components/Arrows/index.ts
  frontend/src/components/Layout/styled.ts
  frontend/src/icons/arrowBack.svg
  frontend/src/icons/arrowForward.svg
  frontend/src/icons/index.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/styled.ts
Labels: bug-fix

#94 Feature/060 - add test model
  backend/migrations/20211219190858-init_collections.js
  backend/migrations/20220125143932-init_collections.js
  backend/src/db/models/ClientCourses.ts
  backend/src/db/models/Course.ts
  backend/src/db/models/Tests.ts
  backend/src/db/models/User.ts
  backend/src/enums/coursesEnums.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Icourses.ts
  backend/src/interfaces/Ientities/Itest.ts
Labels: feature

#92 [feature/v1-053] Added new styles for Menu bar
  frontend/package.json
  frontend/src/api/logOut/index.ts
  frontend/src/api/logOut/logOut.tsx
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Menu/Menu.tsx
  frontend/src/components/Layout/Menu/MenuContainer.tsx
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/constants/menuPaths.tsx
  frontend/src/constants/menuRoles.tsx
  frontend/src/icons/menuIcons/coursesList.svg
  frontend/src/icons/menuIcons/employeeIcon.svg
  frontend/src/icons/menuIcons/helpIcon.svg
  frontend/src/icons/menuIcons/index.ts
  frontend/src/icons/menuIcons/myCourses.svg
  frontend/src/icons/menuIcons/pendingIcon.svg
  frontend/src/icons/menuIcons/skillsIcon.svg
  frontend/src/index.css
  frontend/src/types/menu.ts
  frontend/src/utils/helpers/selectMenuHelpers/getCurrentMenuPath.tsx
  frontend/src/utils/helpers/selectMenuHelpers/index.tsx
  frontend/src/utils/helpers/selectMenuHelpers/removeWrongMenuPath.tsx
  frontend/src/utils/helpers/selectMenuHelpers/setCurrentMenuPath.tsx
  package-lock.json
Labels: feature

#108 bugfix/v1-045/changed skills search
  frontend/package-lock.json
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/UserSkillsContainer.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: bug-fix

#109 [bugfix-feature/v1-024] Updated style for particular mockup
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/utils/helpers/textLimiter.tsx
Labels: bug-fix
