Repository k-krasilnikova/SUL, pull requests merged in 2022-02, with the labels that each got.

#102 fix/V1-048 - refactored logout function
  backend/src/controllers/auth/logout.ts
  backend/src/routing/accountRouter.ts
Labels: required-changes

#104 feature/v1-046/Learning course - video
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/myCourses/getMyCourseInfo.ts
  frontend/src/constants/courseText.tsx
  frontend/src/constants/materials.ts
  frontend/src/icons/index.ts
  frontend/src/icons/playVideo.svg
  frontend/src/index.css
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/types/clientCourse.ts
  frontend/src/utils/helpers/defineMaterialType.ts
  frontend/src/utils/helpers/videoLink.ts
Labels: feature

#110 V1-028 fix: fixed according to QA review
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/utils/helpers/shortify.ts
  frontend/src/utils/helpers/shortifyCourseDescription.ts
  frontend/src/utils/helpers/textLimiter.tsx
Labels: bug-fix

#111 bugfix/v1-052/topbar style fixed
  frontend/src/components/Layout/Header/styled.ts
Labels: bug-fix

#112 bugfix/v1-030/my courses style fixed
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#107 V1-049 feat: implement start the test modal window
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ConfirmDialog/ConfirmDialog.tsx
  frontend/src/components/ConfirmDialog/index.ts
  frontend/src/components/ConfirmDialog/styled.ts
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/icons/close.svg
  frontend/src/icons/index.ts
  frontend/src/images/index.ts
  frontend/src/images/logo_black.png
  frontend/src/images/signInImage.jpeg
  frontend/src/index.css
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/FormDialog/index.ts
  frontend/src/pages/LearningCourse/FormDialog/styled.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/utils/helpers/countdownRenderer.tsx
Labels: feature

#101 feature/V1-078 - endpoint for pending courses
  backend/migrations/20220125143932-init_collections.js
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/db/models/Materials.ts
  backend/src/db/models/User.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/pendingCoursesProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/routing/routes.ts
Labels: required-changes

#115 feature/v1-069/responsive profile page
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/NoContent/styled.ts
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
  frontend/src/pages/Profile/styled.ts
Labels: feature

#116 bugfix/v1-035/learning course fixed
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesList.tsx
Labels: bug-fix

#119 Bugfix/057 - api fix for better UX
  backend/.eslintrc.json
  backend/.prettierrc
  backend/src/config/constants.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/auth/logout.ts
  backend/src/controllers/auth/refresh.ts
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/controllers/clientCourses/passCourse.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/testProvider.ts
  backend/src/interfaces/Iauth/authInterfaces.ts
  backend/src/middlewares/authMiddleware.ts
  backend/src/routing/materialsRouter.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/log/logger.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Labels: bug-fix

#117 [feature/v1-047] Implemented Confirm LogOut Component
  frontend/package-lock.json
  frontend/src/api/logOut/index.ts
  frontend/src/api/logOut/logOut.tsx
  frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
  frontend/src/components/Layout/Header/ConfirmLogOut/index.ts
  frontend/src/components/Layout/Header/ConfirmLogOut/styled.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/constants/authConstants.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/LearningCourse/LearningCourse.tsx
Labels: feature

#121 V1-028 fix: fixed styles according to QA review
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/styled.ts
Labels: bug-fix

#122 V1-049 fix: fixed accoding to QA review
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/FormDialog/styled.ts
Labels: bug-fix

#123 [bugfix-feature/v1-024] Some minor bugfix
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
Labels: bug-fix

#106 Bugfix/v1-065 Lazy loading
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Avatar/Avatar.tsx
  frontend/src/components/Avatar/styled.ts
  frontend/src/components/Loader/styled.ts
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/index.tsx
  frontend/src/components/PDFViewer/styled.js
  frontend/src/components/ProgressBar/index.ts
  frontend/src/index.css
Labels: bug-fix

#114 [bugfix-feature/v1-053] Implemented toggle menu
  backend/package-lock.json
  backend/package.json
  frontend/src/api/logOut/logOut.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/Layout/AuthorizedLayoutContainer.tsx
  frontend/src/components/Layout/Menu/Menu.tsx
  frontend/src/components/Layout/Menu/MenuContainer.tsx
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/components/Layout/styled.ts
  frontend/src/constants/menuPaths.tsx
  frontend/src/icons/menuIcons/index.ts
  frontend/src/icons/menuIcons/leftArrow.svg
  frontend/src/icons/menuIcons/rightArrow.svg
  frontend/src/pages/CoursesList/styled.ts
  frontend/src/types/menu.ts
  frontend/src/types/responseData.ts
  frontend/src/utils/helpers/menuHelpers/getMenuToggle.tsx
  frontend/src/utils/helpers/menuHelpers/removeMenuStatus.tsx
  frontend/src/utils/helpers/menuHelpers/setMenuToggle.tsx
  frontend/src/utils/helpers/selectMenuHelpers/getCurrentMenuPath.tsx
  frontend/src/utils/helpers/selectMenuHelpers/index.tsx
  frontend/src/utils/helpers/selectMenuHelpers/removeWrongMenuPath.tsx
  frontend/src/utils/helpers/selectMenuHelpers/setCurrentMenuPath.tsx
  package-lock.json
Labels: feature, bug-fix

#128 Feature V1-082 - Describing docs for API.
  openApi/SUL-api-docs.yaml
Labels: feature

#129 Bug-fix V1-086 - Fixed mock data related issues, changed tests mock data structure.
  backend/migrations/20220125143932-init_collections.js
  backend/src/db/models/Tests.ts
  backend/src/interfaces/Ientities/Itest.ts
Labels: bug-fix

#130 bugfix/v1-046/video preview quality
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/utils/helpers/videoPlayer/getPreviewId.ts
  frontend/src/utils/helpers/videoPlayer/videoLink.ts
Labels: bug-fix

#131 feature/V1-058
  backend/src/controllers/tests/startTest.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/Ientities/IclientCourses.d.ts
  backend/src/routing/routes.ts
  backend/src/routing/testRouter.ts
Labels: feature

#136 fix/V1-079 - fix eslint error
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/interfaces/Ientities/Iusers.ts
Labels: bug-fix

#139 Bugfix V1-086 - QA comments fixed.
  backend/migrations/20220125143932-init_collections.js
Labels: bug-fix

#137 Feature/v1-084. Error handling implementation.
  backend/.eslintrc.json
  backend/migrations/20220125143932-init_collections.js
  backend/src/app.ts
  backend/src/classes/errors/clientErrors/BadRequestError.ts
  backend/src/classes/errors/clientErrors/ForbiddenError.ts
  backend/src/classes/errors/clientErrors/NotFoundError.ts
  backend/src/classes/errors/clientErrors/UnauthorizedError.ts
  backend/src/classes/errors/common/CommonHttpError.ts
  backend/src/classes/errors/serverErrors/InternalServerError.ts
  backend/src/classes/errors/serverErrors/ServiceUnavailableError.ts
  backend/src/config/constants.ts
  backend/src/controllers/auth/login.ts
  backend/src/controllers/auth/logout.ts
  backend/src/controllers/auth/refresh.ts
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/clientCourses/finishCourse.ts
  backend/src/controllers/clientCourses/getAllClientCourses.ts
  backend/src/controllers/clientCourses/getClientCourse.ts
  backend/src/controllers/clientCourses/passCourse.ts
  backend/src/controllers/clientCourses/startCourse.ts
  backend/src/controllers/courses/getAllCourses.ts
  backend/src/controllers/courses/getCourse.ts
  backend/src/controllers/courses/getMaterials.ts
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/controllers/tests/getTest.ts
  backend/src/controllers/user/getProfileInfo.ts
  backend/src/db/providers/authProvider.ts
  backend/src/db/providers/clientCourseProvider.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/db/providers/pendingCoursesProvider.ts
  backend/src/db/providers/userProvider.ts
  backend/src/interfaces/Ientities/Iusers.ts
  backend/src/interfaces/commonErrorHandling.d.ts
  backend/src/middlewares/authMiddleware.ts
  backend/src/middlewares/connectionMiddleware.ts
  backend/src/middlewares/errorHandlingMiddleware.ts
  backend/src/utils/auth/authUtils.ts
  backend/src/utils/typeGuards/isExpectedHttpError.ts
  openApi/SUL-api-docs.yaml
Labels: feature

#142 V1-067 feat: implement passing the test
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/api/myCourses/getCourseTest.ts
  frontend/src/components/CountDownTimer/CountDownTimer.tsx
  frontend/src/components/CountDownTimer/index.ts
  frontend/src/components/Layout/AuthorizedLayout.tsx
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/constants/sizes.ts
  frontend/src/constants/test.ts
  frontend/src/icons/checkbox.svg
  frontend/src/icons/checkboxChecked.svg
  frontend/src/icons/index.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/QuestionItem/QuestionItem.tsx
  frontend/src/pages/PassingTest/QuestionItem/index.ts
  frontend/src/pages/PassingTest/QuestionItem/styled.ts
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/pages/PassingTest/TestResult/index.ts
  frontend/src/pages/PassingTest/TestResult/styled.ts
  frontend/src/pages/PassingTest/index.ts
  frontend/src/pages/PassingTest/styled.ts
  frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
  frontend/src/pages/index.ts
  frontend/src/types/test.ts
  frontend/src/utils/helpers/countdownRenderer.tsx
Labels: feature

#145 feature/V1-079 - added endpoints for approve and decline pending course
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/enums/routesEnum.ts
  backend/src/routing/pendingCourses.ts
Labels: feature

#146 V1-067 fix: fixed styles according to QA review
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/QuestionItem/styled.ts
  frontend/src/pages/PassingTest/styled.ts
Labels: bug-fix

#148 bugfix/v1-069/no skills margin
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: bug-fix

#147 [bugfix-feature/v1-047] Updated Confirm according to new design
  frontend/src/components/ConfirmDialog/ConfirmDialog.tsx
  frontend/src/components/ConfirmDialog/styled.ts
  frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
  frontend/src/components/Layout/Header/ConfirmLogOut/styled.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Menu/Menu.tsx
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/LearningCourse.tsx
Labels: feature, bug-fix

#151 bugfix/v1-083/responsive layout
  frontend/src/components/ConfirmDialog/styled.ts
  frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
  frontend/src/components/Layout/Header/ConfirmLogOut/styled.tsx
  frontend/src/components/Layout/Header/Header.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/components/Layout/styled.ts
  frontend/src/index.css
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/LearningCourse/FormDialog/styled.ts
  frontend/src/pages/LearningCourse/styled.ts
  frontend/src/pages/Profile/UserSkills/UserSkills.tsx
  frontend/src/pages/Profile/UserSkills/styled.ts
Labels: bug-fix

#150 Bug-fix v1-082 | QA comments fixed:
  openApi/SUL-api-docs.yaml
Labels: bug-fix

#153 fix/V1-059 - clearing course info when we have gotten test info
  frontend/src/api/myCourses/getCourseTest.ts
Labels: bug-fix

#158 fix: fixed styles of NotFound page
  frontend/src/pages/NotFound/styled.ts
Labels: bug, bug-fix

#160 V1-067 fix: fixed an issue with result button
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
Labels: bug, bug-fix

#141 [feature/v1-066] Implemented button loader
  frontend/package-lock.json
  frontend/package.json
  frontend/src/animations/buttonLoader.svg
  frontend/src/animations/buttonSpinner.gif
  frontend/src/animations/index.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/ButtonLoader/ButtonLoader.tsx
  frontend/src/components/ButtonLoader/index.ts
  frontend/src/components/ButtonLoader/styled.ts
  frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
  frontend/src/components/Layout/Header/ConfirmLogOut/styled.tsx
  frontend/src/components/Layout/Header/HeaderContainer.tsx
  frontend/src/components/Layout/styled.ts
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/SignIn/Definition/Definition.tsx
  frontend/src/pages/SignIn/Definition/styled.tsx
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/pages/SignIn/styled.tsx
  frontend/src/types/menu.ts
  frontend/src/types/responseData.ts
  frontend/src/types/signIn.ts
  frontend/src/utils/helpers/menuHelpers/setMenuToggle.tsx
Labels: feature

#155 fix/V1-079 - fixing comments by Hanna
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/tests/startTest.ts
Labels: bug-fix

#163 bugfix/v1-065/help page loader
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/PDFViewerContainer.tsx
Labels: bug-fix

#169 V1-079 - fixing bugs
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/tests/startTest.ts
  backend/src/db/providers/clientCourseProvider.ts
Labels: bug-fix

#172 V1-072 implement responsive Help page
  frontend/src/components/Arrows/arrowBack.tsx
  frontend/src/components/Arrows/arrowForward.tsx
  frontend/src/components/Arrows/styled.ts
  frontend/src/components/PDFViewer/PDFViewer.tsx
  frontend/src/components/PDFViewer/PDFViewerContainer.tsx
  frontend/src/components/PDFViewer/styled.ts
Labels: feature

#175 [bugfix-feature/v1-066] Hot style fix
  frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
Labels: hot-fix

#176 bugfix/v1-083/arrow position in menu
  frontend/src/components/Layout/Menu/styled.ts
  frontend/src/components/Layout/styled.ts
Labels: bug-fix

#177 V1-072 fix: fixed according to QA review
  frontend/src/components/PDFViewer/styled.ts
Labels: bug-fix

#174 V1-088 - fix checking for duplicate
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/db/providers/courseProvider.ts
  backend/src/utils/validation/checkDuplicates.ts
Labels: bug-fix

#164 Feature/080 and 081 - add course to employees
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/manager/applyMiddlewareManager.ts
  backend/src/controllers/manager/getEmployees.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/controllers/pendingCourses/updatePendingCourse.ts
  backend/src/controllers/tests/getAchievments.ts
  backend/src/controllers/tests/getTestResults.ts
  backend/src/controllers/user/applyMiddlewareUser.ts
  backend/src/db/providers/userProvider.ts
  backend/src/enums/routesEnum.ts
  backend/src/interfaces/Imiddlewares/Imiddlewares.ts
  backend/src/routing/clientCoursesRouter.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
  backend/src/routing/routes.ts
  backend/src/utils/validation/checkDuplicates.ts
Labels: feature

#168 feature/detailed course
  frontend/src/App.tsx
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/constants/routes.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/utils/helpers/shortifyCourseDescription.ts
Labels: feature

#181 [bugfix-feature/v1-068] Hot fix SignIn input height
  frontend/src/pages/SignIn/styled.tsx
Labels: hot-fix

#165 feature/v1-070/responsive my courses
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/CourseInfo.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/components/ProgressBar/styled.ts
  frontend/src/constants/statuses.ts
  frontend/src/icons/checkIcon.svg
  frontend/src/icons/index.ts
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/utils/helpers/countCourseProgress.ts
Labels: feature

#184 V1-087 - fixing test and learn course redirect
  backend/src/routing/coursesRouter.ts
  frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#185 bug-fix: fix bug with result counter
  backend/src/db/providers/courseProvider.ts
  backend/src/utils/userTests/userTests.ts
Labels: bug-fix

#194 V1-087 - fix continue button
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#187 V1-073 Implement connection between API and FE for passing test
  frontend/src/App.tsx
  frontend/src/api/test/getCourseTest.ts
  frontend/src/api/test/index.ts
  frontend/src/api/test/sendTestResult.ts
  frontend/src/api/test/startCourseTest.ts
  frontend/src/constants/test.ts
  frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
  frontend/src/pages/PassingTest/PassingTest.tsx
  frontend/src/pages/PassingTest/PassingTestContainer.tsx
  frontend/src/pages/PassingTest/QuestionItem/QuestionItem.tsx
  frontend/src/pages/PassingTest/TestResult/TestResult.tsx
  frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
  frontend/src/types/test.ts
  frontend/src/utils/helpers/convertTestTimeout.ts
Labels: feature

#190 [hotfix/v1-068] removed wrong line
  frontend/src/pages/SignIn/styled.tsx
Labels: hot-fix

#191 Bug-fix/apply middleware
  backend/migrations/20220125143932-init_collections.js
  backend/src/controllers/clientCourses/applyCourse.ts
  backend/src/controllers/manager/adapterManager.ts
  backend/src/controllers/pendingCourses/adapterSender.ts
  backend/src/controllers/pendingCourses/approvePendingCourse.ts
  backend/src/controllers/pendingCourses/declinePendingCourse.ts
  backend/src/controllers/pendingCourses/getPendingCourses.ts
  backend/src/controllers/pendingCourses/updatePendingCourse.ts
  backend/src/controllers/user/adapterUser.ts
  backend/src/interfaces/IResponse/IResponse.ts
  backend/src/interfaces/Imiddlewares/Imiddlewares.ts
  backend/src/routing/coursesRouter.ts
  backend/src/routing/employeesRouter.ts
  backend/src/routing/pendingCourses.ts
Labels: bug-fix

#192 [bugfix-feature/v1-024] adapted styles for truthy work application on deploy
  frontend/src/components/Course/styled.ts
  frontend/src/pages/CoursesList/styled.ts
Labels: hot-fix

#183 feature/v1-070/open course on mobile
  frontend/src/components/Course/Course.tsx
  frontend/src/components/Course/styled.ts
  frontend/src/components/Layout/Header/styled.ts
  frontend/src/components/Layout/styled.ts
  frontend/src/constants/pages.ts
  frontend/src/constants/windowWidth.ts
  frontend/src/icons/backIconMobile.svg
  frontend/src/icons/index.ts
  frontend/src/pages/DetailedCourse/DetailedCourse.tsx
  frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
  frontend/src/pages/DetailedCourse/styled.ts
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/pages/MyCourses/styled.ts
  frontend/src/utils/helpers/shortifyCourseDescription.ts
Labels: feature

#196 bugfix/v1-030/padding on my courses fixed
  frontend/src/pages/MyCourses/styled.ts
Labels: bug-fix

#193 V1-071 Implement responsive design for Courses List
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/CoursesList/styled.ts
Labels: feature

#198 bugfix/v1-054
  frontend/.eslintrc.json
  frontend/src/components/TextField/TextField.tsx
  frontend/src/pages/SignIn/ErrorsMessager/ErrorsContainer.tsx
  frontend/src/pages/SignIn/ErrorsMessager/ErrorsMessenger.tsx
  frontend/src/pages/SignIn/ErrorsMessager/index.ts
  frontend/src/pages/SignIn/SignIn.tsx
  frontend/src/pages/SignIn/SignInContainer.tsx
  frontend/src/types/signIn.ts
  frontend/src/validations/signInValidationSchema.tsx
Labels: feature, bug-fix

#201 [feature-bugfix/courses-padding] Adapted Courses List to new padding
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/CoursesList/styled.ts
Labels: feature, bug-fix

#203 [hot-fix/mobile-width] Updated mobile width for deploy
  frontend/src/components/Course/styled.ts
  frontend/src/pages/CoursesList/styled.ts
Labels: hot-fix

#204 V1-088 - fix
  frontend/src/components/Button/Button.tsx
  frontend/src/pages/CoursesList/CoursesContainer.tsx
  frontend/src/pages/CoursesList/CoursesList.tsx
  frontend/src/pages/MyCourses/MyCoursesContainer.tsx
  frontend/src/pages/MyCourses/MyCoursesList.tsx
  frontend/src/types/responseData.ts
  frontend/src/types/responseDataMyCourses.ts
Labels: bug-fix
